import ArgumentParser
import Foundation

// MARK: - Root command

@main
struct CoreManager: ParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "CoreManager",
        abstract: "Manage libretro core URL lists for Provenance",
        discussion: """
        CoreManager reads CoresRetro/RetroArch/scripts/cores.yml and can generate,
        validate, or diff the URL list files and xcfilelist files used by the build system.
        """,
        subcommands: [
            GenerateCommand.self,
            ValidateCommand.self,
            DiffCommand.self,
            BootstrapCommand.self,
        ],
        defaultSubcommand: GenerateCommand.self
    )
}

// MARK: - Shared options

struct ManifestOptions: ParsableArguments {
    @Option(
        name: [.long, .short],
        help: "Path to cores.yml manifest file"
    )
    var manifest: String?

    /// Resolve the manifest path: explicit --manifest flag, or auto-detect.
    func resolvedManifestURL() throws -> URL {
        if let explicit = manifest {
            return URL(fileURLWithPath: explicit)
        }
        // Auto-detect: walk up from the executable to find the repo root
        let execURL = URL(fileURLWithPath: CommandLine.arguments[0]).standardized
        var dir = execURL.deletingLastPathComponent()
        for _ in 0..<10 {
            let candidate = dir
                .appendingPathComponent("CoresRetro")
                .appendingPathComponent("RetroArch")
                .appendingPathComponent("scripts")
                .appendingPathComponent("cores.yml")
            if FileManager.default.fileExists(atPath: candidate.path) {
                return candidate
            }
            dir = dir.deletingLastPathComponent()
        }
        throw CoreManagerError.manifestNotFound
    }
}

// MARK: - Errors

enum CoreManagerError: Error, CustomStringConvertible {
    case manifestNotFound
    case fileReadError(URL)
    case fileWriteError(URL, Error)
    case validationFailed(Int)

    var description: String {
        switch self {
        case .manifestNotFound:
            return "Could not locate cores.yml. Use --manifest to specify the path."
        case .fileReadError(let url):
            return "Failed to read file: \(url.path)"
        case .fileWriteError(let url, let err):
            return "Failed to write \(url.path): \(err)"
        case .validationFailed(let count):
            return "\(count) URL(s) failed validation."
        }
    }
}

// MARK: - File paths

func outputFiles(for manifestURL: URL) -> [String: URL] {
    let scriptsDir = manifestURL.deletingLastPathComponent()
    return [
        "urls_ios":           scriptsDir.appendingPathComponent("urls.txt"),
        "urls_appstore_ios":  scriptsDir.appendingPathComponent("urls-appstore.txt"),
        "urls_tvos":          scriptsDir.appendingPathComponent("urls-tv.txt"),
        "urls_appstore_tvos": scriptsDir.appendingPathComponent("urls-appstore-tv.txt"),
        "xcf_ios":            scriptsDir.appendingPathComponent("output_modules.xcfilelist"),
        "xcf_appstore_ios":   scriptsDir.appendingPathComponent("output_modules_appstore_ios.xcfilelist"),
        "xcf_tvos":           scriptsDir.appendingPathComponent("output_modules_tv.xcfilelist"),
        "xcf_appstore_tvos":  scriptsDir.appendingPathComponent("output_modules_appstore_tv.xcfilelist"),
    ]
}

// MARK: - Content generators

let autoGeneratedHeader = """
    # Auto-generated by Scripts/CoreManager — do not edit manually
    # Edit CoresRetro/RetroArch/scripts/cores.yml and re-run:
    #   swift run CoreManager generate

    """

let xcfilelistPrefix = "$(SRCROOT)/CoresRetro/RetroArch/modules/"

func generateURLFile(
    cores: [CoreEntry],
    buildbot: BuildbotConfig,
    platform: String,       // "ios" | "tvos"
    appstore: Bool
) -> String {
    var lines = [autoGeneratedHeader]
    for core in cores {
        let url = platform == "ios"
            ? core.iosURL(buildbot: buildbot)
            : core.tvosURL(buildbot: buildbot)

        let isDisabled = !core.enabled
        let isExcluded = appstore && !core.appstore

        if isDisabled || isExcluded {
            lines.append("#\(url)\n")
        } else {
            lines.append("\(url)\n")
        }
    }
    return lines.joined()
}

func generateXCFilelist(
    cores: [CoreEntry],
    platform: String,       // "ios" | "tvos"
    appstore: Bool
) -> String {
    var lines = [autoGeneratedHeader]
    for core in cores {
        // Disabled cores are omitted entirely from xcfilelists
        guard core.enabled else { continue }
        // Appstore-excluded cores are omitted from appstore xcfilelists
        if appstore && !core.appstore { continue }

        let fname = platform == "ios" ? core.iosFilename : core.tvosFilename
        lines.append("\(xcfilelistPrefix)\(fname)\n")
    }
    return lines.joined()
}

// MARK: - generate subcommand

struct GenerateCommand: ParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "generate",
        abstract: "Generate all output files from cores.yml"
    )

    @OptionGroup var manifestOptions: ManifestOptions

    @Flag(name: .long, help: "Print what would be written without writing files")
    var dryRun: Bool = false

    @Flag(name: .shortAndLong, help: "Show additional output")
    var verbose: Bool = false

    mutating func run() throws {
        let manifestURL = try manifestOptions.resolvedManifestURL()
        let manifest = try CoreManifest.load(from: manifestURL)
        let files = outputFiles(for: manifestURL)

        let allIOS = manifest.iosCores(appstore: false)
        let allTVOS = manifest.tvosCores(appstore: false)

        let outputs: [(String, String)] = [
            ("urls_ios",           generateURLFile(cores: allIOS,  buildbot: manifest.buildbot, platform: "ios",  appstore: false)),
            ("urls_appstore_ios",  generateURLFile(cores: allIOS,  buildbot: manifest.buildbot, platform: "ios",  appstore: true)),
            ("urls_tvos",          generateURLFile(cores: allTVOS, buildbot: manifest.buildbot, platform: "tvos", appstore: false)),
            ("urls_appstore_tvos", generateURLFile(cores: allTVOS, buildbot: manifest.buildbot, platform: "tvos", appstore: true)),
            ("xcf_ios",            generateXCFilelist(cores: allIOS,  platform: "ios",  appstore: false)),
            ("xcf_appstore_ios",   generateXCFilelist(cores: allIOS,  platform: "ios",  appstore: true)),
            ("xcf_tvos",           generateXCFilelist(cores: allTVOS, platform: "tvos", appstore: false)),
            ("xcf_appstore_tvos",  generateXCFilelist(cores: allTVOS, platform: "tvos", appstore: true)),
        ]

        for (key, content) in outputs {
            guard let url = files[key] else { continue }
            if dryRun {
                let lineCount = content.components(separatedBy: .newlines).count
                print("[dry-run] Would write \(lineCount) lines to \(url.lastPathComponent)")
                if verbose {
                    print(content)
                }
            } else {
                do {
                    try content.write(to: url, atomically: true, encoding: .utf8)
                    print("  Written: \(url.path)")
                } catch {
                    throw CoreManagerError.fileWriteError(url, error)
                }
            }
        }

        if !dryRun {
            print("Done.")
        }
    }
}

// MARK: - validate subcommand

struct ValidateCommand: ParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "validate",
        abstract: "HTTP HEAD check all URLs in the manifest"
    )

    @OptionGroup var manifestOptions: ManifestOptions

    @Flag(name: .shortAndLong, help: "Show additional output")
    var verbose: Bool = false

    mutating func run() throws {
        let manifestURL = try manifestOptions.resolvedManifestURL()
        let manifest = try CoreManifest.load(from: manifestURL)

        var urls: [(String, URL)] = []
        var seen = Set<String>()

        func collect(_ cores: [CoreEntry], platform: String) {
            for core in cores where core.enabled {
                let urlStr = platform == "ios"
                    ? core.iosURL(buildbot: manifest.buildbot)
                    : core.tvosURL(buildbot: manifest.buildbot)
                if !seen.contains(urlStr) {
                    seen.insert(urlStr)
                    if let url = URL(string: urlStr) {
                        urls.append((core.name, url))
                    }
                }
            }
        }

        collect(manifest.iosCores(), platform: "ios")
        collect(manifest.tvosCores(), platform: "tvos")

        print("Validating \(urls.count) URLs...")

        let semaphore = DispatchSemaphore(value: 0)
        var failures = 0
        let group = DispatchGroup()
        let lock = NSLock()

        for (name, url) in urls {
            group.enter()
            var request = URLRequest(url: url)
            request.httpMethod = "HEAD"
            request.timeoutInterval = 15

            URLSession.shared.dataTask(with: request) { _, response, error in
                defer { group.leave() }
                let status: String
                let ok: Bool
                if let http = response as? HTTPURLResponse {
                    status = "\(http.statusCode)"
                    ok = http.statusCode < 400
                } else if let err = error {
                    status = err.localizedDescription
                    ok = false
                } else {
                    status = "???"
                    ok = false
                }

                lock.lock()
                if !ok { failures += 1 }
                lock.unlock()

                let marker = ok ? "OK  " : "FAIL"
                print("  [\(marker)] \(status.padding(toLength: 3, withPad: " ", startingAt: 0))  \(url)")
            }.resume()
        }

        group.notify(queue: .main) {
            semaphore.signal()
        }
        semaphore.wait()

        print("\n\(urls.count) checked, \(failures) failures.")
        if failures > 0 {
            throw CoreManagerError.validationFailed(failures)
        }
    }
}

// MARK: - diff subcommand

struct DiffCommand: ParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "diff",
        abstract: "Show diff between current files and what would be generated"
    )

    @OptionGroup var manifestOptions: ManifestOptions

    mutating func run() throws {
        let manifestURL = try manifestOptions.resolvedManifestURL()
        let manifest = try CoreManifest.load(from: manifestURL)
        let files = outputFiles(for: manifestURL)

        let allIOS = manifest.iosCores(appstore: false)
        let allTVOS = manifest.tvosCores(appstore: false)

        let outputs: [(String, String)] = [
            ("urls_ios",           generateURLFile(cores: allIOS,  buildbot: manifest.buildbot, platform: "ios",  appstore: false)),
            ("urls_appstore_ios",  generateURLFile(cores: allIOS,  buildbot: manifest.buildbot, platform: "ios",  appstore: true)),
            ("urls_tvos",          generateURLFile(cores: allTVOS, buildbot: manifest.buildbot, platform: "tvos", appstore: false)),
            ("urls_appstore_tvos", generateURLFile(cores: allTVOS, buildbot: manifest.buildbot, platform: "tvos", appstore: true)),
            ("xcf_ios",            generateXCFilelist(cores: allIOS,  platform: "ios",  appstore: false)),
            ("xcf_appstore_ios",   generateXCFilelist(cores: allIOS,  platform: "ios",  appstore: true)),
            ("xcf_tvos",           generateXCFilelist(cores: allTVOS, platform: "tvos", appstore: false)),
            ("xcf_appstore_tvos",  generateXCFilelist(cores: allTVOS, platform: "tvos", appstore: true)),
        ]

        var anyDiff = false

        for (key, generated) in outputs {
            guard let url = files[key] else { continue }
            let current: String
            if FileManager.default.fileExists(atPath: url.path),
               let data = FileManager.default.contents(atPath: url.path),
               let text = String(data: data, encoding: .utf8) {
                current = text
            } else {
                current = ""
            }

            if current != generated {
                anyDiff = true
                print("--- current/\(url.lastPathComponent)")
                print("+++ generated/\(url.lastPathComponent)")
                printSimpleDiff(from: current, to: generated)
                print()
            }
        }

        if !anyDiff {
            print("No differences — generated output matches existing files.")
        }
    }

    private func printSimpleDiff(from old: String, to new: String) {
        let oldLines = old.components(separatedBy: .newlines)
        let newLines = new.components(separatedBy: .newlines)
        let oldSet = Set(oldLines)
        let newSet = Set(newLines)

        for line in oldLines where !newSet.contains(line) {
            print("- \(line)")
        }
        for line in newLines where !oldSet.contains(line) {
            print("+ \(line)")
        }
    }
}

// MARK: - bootstrap subcommand

struct BootstrapCommand: ParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "bootstrap",
        abstract: "Read existing txt files and print a starter YAML"
    )

    @OptionGroup var manifestOptions: ManifestOptions

    mutating func run() throws {
        let manifestURL = try manifestOptions.resolvedManifestURL()
        let scriptsDir = manifestURL.deletingLastPathComponent()

        print("# Bootstrap output — cores derived from existing txt files")
        print("# Review and merge into cores.yml as needed")
        print()

        let iosURL      = scriptsDir.appendingPathComponent("urls.txt")
        let iosAsURL    = scriptsDir.appendingPathComponent("urls-appstore.txt")
        let tvosURL     = scriptsDir.appendingPathComponent("urls-tv.txt")
        let tvosAsURL   = scriptsDir.appendingPathComponent("urls-appstore-tv.txt")

        let iosEntries      = parseURLFile(at: iosURL)
        let iosAsEntries    = parseURLFile(at: iosAsURL)
        let tvosEntries     = parseURLFile(at: tvosURL)
        let tvosAsEntries   = parseURLFile(at: tvosAsURL)

        let iosEnabled  = Set(iosEntries.filter { $0.enabled }.map { $0.filename })
        let iosAsEnabled = Set(iosAsEntries.filter { $0.enabled }.map { $0.filename })
        let tvosEnabled = Set(tvosEntries.filter { $0.enabled }.map { $0.filename })
        let tvosAsEnabled = Set(tvosAsEntries.filter { $0.enabled }.map { $0.filename })

        var all: [String: [String: Any]] = [:]

        func register(filename: String, platform: String, enabled: Bool) {
            let (name, custom) = coreNameFrom(filename: filename)
            if all[name] == nil {
                all[name] = [
                    "name": name,
                    "ios": false,
                    "tvos": false,
                    "appstore": true,
                    "enabled": true,
                ]
                if let c = custom { all[name]!["filename"] = c }
            }
            if platform == "ios" { all[name]!["ios"] = true }
            else { all[name]!["tvos"] = true }
        }

        for entry in iosEntries {
            register(filename: entry.filename, platform: "ios", enabled: entry.enabled)
            if entry.enabled && !iosAsEnabled.contains(entry.filename) {
                all[coreNameFrom(filename: entry.filename).0]!["appstore"] = false
            }
        }

        for entry in tvosEntries {
            register(filename: entry.filename, platform: "tvos", enabled: entry.enabled)
            if entry.enabled && !tvosAsEnabled.contains(entry.filename) {
                all[coreNameFrom(filename: entry.filename).0]!["appstore"] = false
            }
        }

        print("cores:")
        for name in all.keys.sorted() {
            let entry = all[name]!
            print("  - name: \(name)")
            print("    ios: \(entry["ios"] as? Bool == true ? "true" : "false")")
            print("    tvos: \(entry["tvos"] as? Bool == true ? "true" : "false")")
            print("    appstore: \(entry["appstore"] as? Bool == true ? "true" : "false")")
            let iosFile = "\(name)_libretro_ios.dylib"
            let tvosFile = "\(name)_libretro_tvos.dylib"
            let iosDisabled = !iosEnabled.contains(iosFile)
            let tvosDisabled = !tvosEnabled.contains(tvosFile)
            let bothDisabled = (entry["ios"] as? Bool == true) && (entry["tvos"] as? Bool == true)
                ? iosDisabled && tvosDisabled
                : (entry["ios"] as? Bool == true ? iosDisabled : tvosDisabled)
            print("    enabled: \(bothDisabled ? "false" : "true")")
            if let fname = entry["filename"] as? String {
                print("    filename: \"\(fname)\"")
            }
            print()
        }
    }

    private struct URLEntry { let enabled: Bool; let filename: String }

    private func parseURLFile(at url: URL) -> [URLEntry] {
        guard let text = try? String(contentsOf: url, encoding: .utf8) else { return [] }
        return text.components(separatedBy: .newlines).compactMap { line in
            let t = line.trimmingCharacters(in: .whitespaces)
            guard !t.isEmpty else { return nil }
            let enabled = !t.hasPrefix("#")
            let urlStr = t.hasPrefix("#") ? String(t.dropFirst()) : t
            var fname = urlStr.components(separatedBy: "/").last ?? urlStr
            if fname.hasSuffix(".zip") { fname = String(fname.dropLast(4)) }
            return URLEntry(enabled: enabled, filename: fname)
        }
    }

    private func coreNameFrom(filename: String) -> (String, String?) {
        var base = filename
        if base.hasSuffix(".dylib") { base = String(base.dropLast(6)) }
        if base.hasSuffix("_libretro_ios") {
            return (String(base.dropLast(13)), nil)
        } else if base.hasSuffix("_libretro_tvos") {
            return (String(base.dropLast(14)), nil)
        }
        // Platform-neutral
        let name = base.replacingOccurrences(of: "_libretro", with: "")
        return (name, filename)
    }
}
