mednafen_SOURCES	+=      nes/boards/8237.cpp nes/boards/h2288.cpp nes/boards/simple.cpp nes/boards/super24.cpp nes/boards/mmc2and4.cpp nes/boards/vrc6.cpp nes/boards/emu2413.cpp nes/boards/vrc7.cpp nes/boards/96.cpp nes/boards/208.cpp nes/boards/187.cpp nes/boards/95.cpp nes/boards/fme7.cpp nes/boards/mmc5.cpp nes/boards/mmc3.cpp nes/boards/mmc1.cpp nes/boards/tengen.cpp nes/boards/90.cpp nes/boards/deirom.cpp nes/boards/n106.cpp nes/boards/maxicart.cpp
mednafen_SOURCES	+=	nes/boards/112.cpp nes/boards/113.cpp nes/boards/114.cpp nes/boards/117.cpp nes/boards/22.cpp nes/boards/23.cpp nes/boards/25.cpp nes/boards/67.cpp nes/boards/68.cpp nes/boards/16.cpp nes/boards/97.cpp nes/boards/99.cpp nes/boards/151.cpp nes/boards/180.cpp nes/boards/182.cpp nes/boards/184.cpp
mednafen_SOURCES	+=	nes/boards/88.cpp nes/boards/89.cpp nes/boards/92.cpp nes/boards/86.cpp nes/boards/82.cpp nes/boards/80.cpp nes/boards/18.cpp nes/boards/21.cpp nes/boards/228.cpp nes/boards/234.cpp nes/boards/232.cpp
mednafen_SOURCES	+=	nes/boards/42.cpp nes/boards/ffe.cpp nes/boards/65.cpp nes/boards/nina06.cpp nes/boards/73.cpp nes/boards/32.cpp nes/boards/33.cpp nes/boards/41.cpp nes/boards/46.cpp nes/boards/72.cpp nes/boards/75.cpp nes/boards/76.cpp nes/boards/77.cpp nes/boards/colordreams.cpp
mednafen_SOURCES	+=	nes/boards/140.cpp nes/boards/93.cpp nes/boards/94.cpp nes/boards/malee.cpp nes/boards/156.cpp nes/boards/supervision.cpp nes/boards/novel.cpp nes/boards/242.cpp nes/boards/246.cpp nes/boards/248.cpp nes/boards/15.cpp nes/boards/8.cpp nes/boards/193.cpp nes/boards/189.cpp
mednafen_SOURCES	+=	nes/boards/244.cpp nes/boards/sachen.cpp nes/boards/107.cpp nes/boards/51.cpp nes/boards/152.cpp nes/boards/70.cpp nes/boards/185.cpp nes/boards/78.cpp nes/boards/87.cpp nes/boards/34.cpp nes/boards/222.cpp nes/boards/codemasters.cpp nes/boards/38.cpp

mednafen_SOURCES	+=	nes/boards/240.cpp nes/boards/241.cpp nes/boards/163.cpp

mednafen_SOURCES	+=	nes/boards/30.cpp nes/boards/190.cpp

mednafen_SOURCES	+=	nes/boards/40.cpp
