# These are supported funding model platforms

github: [JoeMatt]
patreon: provenance
open_collective: provenanceemu
buy_me_a_coffee: joemattiello
custom: ['https://provenance-emu.com/plus/', 'https://provenance-emu.com/donate/']
