.TH LIBPNGPF 3 "May 1, 2025"
.SH NAME
libpng \- Portable Network Graphics (PNG) Reference Library 1.6.49.git

.SH SYNOPSIS
\fB#include "pngpriv.h"\fP

.SH DESCRIPTION
As of libpng version 1.5.1, this manual is no longer maintained.  The private
function prototypes, declared in private header files, should not be accessed
by applications.

.SH "SEE ALSO"
.BR "libpng"(3)

.SH AUTHORS
Cosmin Truta, Glenn Randers-Pehrson
