disabled_rules:
  - block_based_kvo
  - colon
  - control_statement
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - file_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - multiple_closures_with_trailing_closure
  - nesting
  - switch_case_alignment
  - todo
  - type_name
  - type_body_length
  - function_body_length
  - unused_closure_parameter

# parameterized rules can be customized from this configuration file
line_length: 200
# parameterized rules are first parameterized as a warning level, then error level.
type_body_length:
  - 300 # warning
  - 600 # error
# parameterized rules are first parameterized as a warning level, then error level.
# identifier_name_max_length:
#   - 40 # warning
#   - 60 # error
# # parameterized rules are first parameterized as a warning level, then error level.
# identifier_name_min_length:
#   - 3 # warning
#   - 2 # error
function_body_length:
  - 200 # warning
  - 500 # error
large_tuple:
  - 4 # warning
  - 6 # error

opt_in_rules:
  - empty_count
  - force_unwrapping

included:
  - Provenance
  - Provenance Tests
  - ProvenanceShared
  - ProvenanceShared-tvOS
  - ProvenanceTV
  - PVLibrary
  - PVSupport
  - Spotlight
  - TopShelf

excluded: # paths to ignore during linting. overridden byincluded.
  - Carthage
  - PVSupport/Carthage
  - PVLibrary/Carthage
  - Pods
  - Cores
  - Scripts
  - fastlane
  - build
  - archive
  - .build

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# Override these rules to be warnings for now
force_cast: warning
force_try: warning
empty_count: warning

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)

custom_rules:
  placeholders_in_comments:
    included: ".*\\.swift"
    name: "No Placeholders in Comments"
    regex: "<#([^#]+)#>"
    match_kinds:
      - comment
      - doccomment
    message: "Placeholder left in comment."
  tiles_deprecated:
    included: ".*\\.swift"
    name: "Tiles are deprecated in favor of Frame"
    regex: "([T,t]ile$|^[T,t]il[e,es])"
    message: "Tiles are deprecated in favor of Frame"
    severity: warning

