name: Provenance-SPM

# include:
#   - base_spec.yml

############
# Options
############

options:
  bundleIdPrefix: com.provenance
  createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
  defaultConfig: Release
  deploymentTarget:
    iOS: "13.0"
    macOS: "10.15"
    tvOS: "13.0"
    watchOS: "6.0"
  developmentLanguage: en
  generateEmptyDirectories: false
  groupSortPosition: top
  indentWidth: 4
  minimumXcodeGenVersion: 2.10
  tabWidth: 4
  usesTabs: false

############
# fileGroups
############

# fileGroups:
#   - config

############
# Configs
############

configs:
  Debug: debug
  Release: release
  Adhoc: release
  Beta: release
  AppStore: release

############
# Settings
############

settings:
  base:
    LD_RUNPATH_SEARCH_PATHS:
      - /usr/lib/swift
      - $(inherited)
    LIBRARY_SEARCH_PATHS:
      - $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
      - $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
      - $(inherited)
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
    GCC_C_LANGUAGE_STANDARD: gnu99
    CLANG_CXX_LANGUAGE_STANDARD: gnu++11
  configs:
    Debug:
      COPY_PHASE_STRIP: false
      GCC_SYMBOLS_PRIVATE_EXTERN: false
      MTL_ENABLE_DEBUG_INFO: true
      SWIFT_COMPILATION_MODE: single
    Release:
      COPY_PHASE_STRIP: true
      GCC_SYMBOLS_PRIVATE_EXTERN: true
      MTL_ENABLE_DEBUG_INFO: false
      SWIFT_COMPILATION_MODE: wholemodule

############
# Pods
############


  # https://cocoapods.org/pods/ChartsRealm
  # https://github.com/danielgindi/ChartsRealm
  # SwiftPM: false
  # ChartsRealm:

# package-groups:
#   firebase: [Auth, Analytics, Crashlytics, Storage]
#   facebook: [Login, Share]

############
# Packages
############

packages:
  QuickTableViewController:
    url: https://github.com/bcylin/QuickTableViewController
    from: 1.3.1
  SteamController:
    url: https://github.com/zydeco/SteamController
    from: 1.2
  # PVSupport
  CocoaLumberjack:
    url: https://github.com/CocoaLumberjack/CocoaLumberjack
    from: 3.7.2
  Reachability.swift:
    url: https://github.com/ashleymills/Reachability.swift
    from: 5.1.0
  # PVLibrary
  ZipArchive:
    url: https://github.com/ZipArchive/ZipArchive
    from: 2.4.2
  realm-cocoa:
    url: https://github.com/realm/realm-cocoa
    from: 10.8.1
  SQLite.swift:
    url: https://github.com/stephencelis/SQLite.swift
    from: 0.12.2
  # Rx
  RxRealm:
    url: https://github.com/RxSwiftCommunity/RxRealm
    from: 5.0.2
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    from: 6.2.0

############
# Targets
############

targets:
  ############
  # Provenance
  ############
  Provenance:
    type: application
    platform: [iOS, tvOS]
    
    # sources
    sources: [Provenance]
    
    # settings
    base:
      PRODUCT_BUNDLE_IDENTIFIER: com.bundleident.provenance
      INFOPLIST_FILE: Provenance/Provenance-Info.plist
      CODE_SIGN_ENTITLEMENTS: Provenance/Provenance.entitlements # Provenance/Provenance-Free.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      #SWIFT_OBJC_BRIDGING_HEADER: Provenance/Provenance-Bridging-Header.h
      GCC_PREFIX_HEADER: Provenance/Provenance-Prefix.pch
    configs:
      Debug:
        CODE_SIGN_IDENTITY: "iPhone Developer"
        PROVISIONING_PROFILE_SPECIFIER: "match Development org.provenance-emu.provenance"
      Release:
        CODE_SIGN_IDENTITY: "iPhone Distribution"
        PROVISIONING_PROFILE_SPECIFIER: "match AdHoc org.provenance-emu.provenance"
        SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"

    # scheme
    scheme:
      gatherCoverageData: true

    # dependencies
    dependencies:
      - target: [PVSupport, PVLibrary]
      - sdk: AudioToolbox.framework
      - sdk: AVFoundation.framework
      - sdk: CFNetwork.framework
      - sdk: CoreData.framework
      - sdk: CoreGraphics.framework
      - sdk: CoreServices.framework
      - sdk: Foundation.framework
      - sdk: GameController.framework
      - sdk: GLKit.framework
      - sdk: OpenGLES.framework
      - sdk: Photos.framework
      - sdk: Security.framework
      - sdk: UIKit.framework
      - package: QuickTableViewController
      - package: SteamController
    # scripts
    postCompileScripts:
      # swiftlint
      - script: mint run swiftlint swiftlint --config .swiftlint.xcode.yml
        name: ⚠️ Swiftlint
        showEnvVars: false

  # -----------
  # TopShelf
  # -----------

  TopShelf:
    platform: tvOS
    type: app-extension

    # sources
    sources: [TopShelf]
    
    # dependencies
    dependencies:
      - target: [PVSupport, PVLibrary]
      - sdk: Foundation.framework
      - sdk: TVServices.framework

  # -----------
  # Spotlight
  # -----------

  Spotlight:
    platform: iOS
    type: app-extension

    # sources
    sources: [Spotlight]

    # dependencies
    dependencies:
      - target: [PVSupport, PVLibrary]
      - sdk: CoreServices.framework
      - package: CocoaLumberjack
      - package: Realm
      - package: RealmSwift
  ############
  # PVSupport
  ############

  PVSupport:
    type: framework
    platform: [iOS, tvOS]

    # sources
    sources: [PVSupport]
    
    # settings
    base:
      PRODUCT_BUNDLE_IDENTIFIER: com.bundleident.PVSupport
      INFOPLIST_FILE: PVSupport/PVSupport/PVSupport.plist
      #SWIFT_OBJC_BRIDGING_HEADER: PVSupport/PVSupport/PVSupport.h
      GCC_PREFIX_HEADER: PVSupport/PVSupport/PVSupport-Prefix.pch
    configs:
      Debug:
      Release:
        SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"

    # scheme
    scheme:
      gatherCoverageData: true

    # dependencies
    dependencies:
      - sdk: Foundation.framework
      - sdk: GameController.framework
      - package: CocoaLumberjack
    # scripts
    postCompileScripts:
      # swiftlint
      - script: mint run swiftlint swiftlint --config .swiftlint.xcode.yml
        name: Swiftlint
        showEnvVars: false

############
# Include
############

# include:
#   - path: xcodegen/project_ios.yml
#     relativePaths: false
#   - path: xcodegen/project_tvos.yml
#     relativePaths: false
#   - path: xcodegen/project_watchos.yml
#     relativePaths: false
#   - path: xcodegen/project_macos.yml
#     relativePaths: false

# schemes:
#   TestStickers:
#     build:
#       targets:
#         TestStickersExtension: all
#         TestStickers: all
#       parallelizeBuild: true
#       buildImplicitDependencies: true
#     run:
#       launchAutomaticallySubstyle: 2