name: Provenance

# include:
#   - base_spec.yml

############
# Options
############

options:
  bundleIdPrefix: com.provenance
  createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
  defaultConfig: Release
  deploymentTarget:
    iOS: "13.0"
    macOS: "10.15"
    tvOS: "13.0"
    watchOS: "6.0"
  developmentLanguage: en
  generateEmptyDirectories: false
  groupSortPosition: top
  indentWidth: 4
  minimumXcodeGenVersion: 2.10
  tabWidth: 4
  usesTabs: false

############
# fileGroups
############

# fileGroups:
#   - config

############
# Configs
############

configs:
  Debug: debug
  Release: release
  Adhoc: release
  Beta: release
  AppStore: release

############
# Settings
############

settings:
  base:
    LD_RUNPATH_SEARCH_PATHS:
      - /usr/lib/swift
      - $(inherited)
    LIBRARY_SEARCH_PATHS:
      - $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
      - $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
      - $(inherited)
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
    GCC_C_LANGUAGE_STANDARD: gnu99
    CLANG_CXX_LANGUAGE_STANDARD: gnu++11
  configs:
    Debug:
      COPY_PHASE_STRIP: false
      GCC_SYMBOLS_PRIVATE_EXTERN: false
      MTL_ENABLE_DEBUG_INFO: true
      SWIFT_COMPILATION_MODE: single
    Release:
      COPY_PHASE_STRIP: true
      GCC_SYMBOLS_PRIVATE_EXTERN: true
      MTL_ENABLE_DEBUG_INFO: false
      SWIFT_COMPILATION_MODE: wholemodule

############
# Pods
############


  # https://cocoapods.org/pods/ChartsRealm
  # https://github.com/danielgindi/ChartsRealm
  # SwiftPM: false
  # ChartsRealm:

package-groups:
  firebase: [Auth, Analytics, Crashlytics, Storage]
  facebook: [Login, Share]

############
# Packages
############

############
# Targets
############

targets:
  Provenance:
    type: application
    platform: [iOS, tvOS]
    
    # sources
    sources: [Provenance]
    
    # settings
    base:
      PRODUCT_BUNDLE_IDENTIFIER: com.provenance-emu.provenance
      INFOPLIST_FILE: Provenance/Provenance-Info.plist
      CODE_SIGN_ENTITLEMENTS: Provenance/Provenance.entitlements # Provenance/Provenance-Free.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      #SWIFT_OBJC_BRIDGING_HEADER: Provenance/Provenance-Bridging-Header.h
      GCC_PREFIX_HEADER: Provenance/Provenance-Prefix.pch
    configs:
      Debug:
        CODE_SIGN_IDENTITY: "iPhone Developer"
        PROVISIONING_PROFILE_SPECIFIER: "match Development com.provenance-emu.provenance"
      Release:
        CODE_SIGN_IDENTITY: "iPhone Distribution"
        PROVISIONING_PROFILE_SPECIFIER: "match AdHoc com.provenance-emu.provenance"
        SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"

    # scheme
    scheme:
      gatherCoverageData: true

    # dependencies
    dependencies:
      # - target: FitnessKit_${platform}
      - sdk: AudioToolbox.framework
      - sdk: AVFoundation.framework
      - sdk: iAd.f ramework
      - package: ActionSheetPicker-3.0
      - package: Alamofire
      - package: AppsFlyerLib
      - package: Branch
      - package: Cache
      - package: Charts
      - package: Cosmos
      - package: CountryCode
      - package: Eureka
      - package: FacebookLogin
      - package: FacebookShare
      - package: FloatingPanel
      - package: Fuse
      - package: Intercom
      - package: JTAppleCalendar
      - package: Lottie
      - package: Mixpanel
      - package: PhoneNumberKit
      - package: Purchases
      - package: Reachability
      - package: RealmSwift
      - package: SDWebImage
      - package: ShareThatTo
      - package: Shuffle
      - package: SwiftyJSON
      - package: FirebaseAuth
      - package: FirebaseAnalytics
      - package: FirebaseCrashlytics
      - package: FirebaseStorage

    # scripts
    postCompileScripts:
      # swiftlint
      - script: mint run swiftlint swiftlint --config .swiftlint.xcode.yml
        name: Swiftlint
        showEnvVars: false

  # -----------
  # Provenance UI Tests
  # -----------

  # Provenance UI Tests:
  #   type: bundle.unit-test
  #   platform: [iOS] #[iOS, watchOS, tvOS]

  #   # sources
  #   sources:
  #     - Provenance UI Tests

  #   # dependencies
  #   dependencies:
  #     - target: Provenance_${platform}

  #   # scripts
  #   postCompileScripts:
  #     # swiftlint
  #     - script: mint run swiftlint swiftlint --config .swiftlint.xcode.yml
  #       name: Swiftlint

  # -----------
  # FitnessKit
  # -----------

  # FitnessKit:
  #   type: framework
  #   platform: iOS #[iOS, watchOS, tvOS]

  #   # settings
  #   # settings:

  #   # scheme
  #   # scheme:
  #     # gatherCoverageData: true
  #     # testTargets:
  #     #   - name: FitnessKitTests_${platform}
  #     #     parallelizable: true
  #     #     randomExecutionOrder: true

  #   #sources
  #   sources: [FitnessKit]
  
  #   # dependencies
  #   dependencies:
  #     - package: ActionSheetPicker-3.0
  #     - package: Alamofire
  #     - package: AppsFlyerLib
  #     - package: Branch
  #     - package: Cache
  #     - package: Charts
  #     - package: Cosmos
  #     - package: CountryCode
  #     - package: Eureka
  #     - package: FacebookLogin
  #     - package: FacebookShare
  #     - package: FloatingPanel
  #     - package: Fuse
  #     - package: Intercom
  #     - package: JTAppleCalendar
  #     - package: Lottie
  #     - package: Mixpanel
  #     - package: PhoneNumberKit
  #     - package: Purchases
  #     - package: Reachability
  #     - package: RealmSwift
  #     - package: SDWebImage
  #     - package: ShareThatTo
  #     - package: Shuffle
  #     - package: SwiftyJSON
  #     - package: FirebaseAuth
  #     - package: FirebaseAnalytics
  #     - package: FirebaseCrashlytics
  #     - package: FirebaseStorage
  
  # -----------
  # FitnessKitTests
  # -----------

  # FitnessKitTests:
  #   type: bundle.unit-test
  #   platform: [iOS] #[iOS, watchOS, tvOS]

  #   # sources
  #   sources:
  #     - FitnessKitTests

  #   # dependencies
  #   dependencies:
  #     - target: FitnessKit_${platform}

  #   # scripts
  #   postCompileScripts:
  #     # swiftlint
  #     - script: mint run swiftlint swiftlint --config .swiftlint.xcode.yml
  #       name: Swiftlint

  # -----------
  # FitnessKitUI
  # -----------

  # FitnessKitUI:
  #   type: framework
  #   platform: iOS
  #   sources: [FitnessKitUI]
  
  # -----------
  # Widget
  # -----------

  # Widget:
  #   type: app-extension
  #   platform: [iOS]

  #   # settings
  #   settings:
  #     base:
  #       PRODUCT_BUNDLE_IDENTIFIER: com.jakemor.firness-ai.Widget
  #       INFOPLIST_FILE: Widget/Info.plist

  #   # sources
  #   sources: Widget

  #   # dependencies
  #   dependencies:
  #     - target: FitnessKit_${platform}

  # -----------
  # MyFrameworkTests
  # -----------

  # MyFrameworkTests:
  #   type: bundle.unit-test
  #   platform: [iOS, macOS, watchOS, tvOS]

  #   # sources
  #   sources:
  #     - Tests

  #   # dependencies
  #   dependencies:
  #     - target: MyFramework_${platform}

  #   # scripts
  #   postCompileScripts:
  #     # swiftlint
  #     - script: mint run swiftlint swiftlint --config .swiftlint.yml
  #       name: Swiftlint

############
# Include
############

# include:
#   - path: xcodegen/project_ios.yml
#     relativePaths: false
#   - path: xcodegen/project_tvos.yml
#     relativePaths: false
#   - path: xcodegen/project_watchos.yml
#     relativePaths: false
#   - path: xcodegen/project_macos.yml
#     relativePaths: false

# schemes:
#   TestStickers:
#     build:
#       targets:
#         TestStickersExtension: all
#         TestStickers: all
#       parallelizeBuild: true
#       buildImplicitDependencies: true
#     run:
#       launchAutomaticallySubstyle: 2