# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../ppsspp/ext/armips/ext/filesystem/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/CMakeDependentOption.cmake))

../cmake/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/lib/python3.10/site-packages/cmake/data/bin/cmake -H../ppsspp -B../cmake
