included:
  - Source
  - Example
disabled_rules:
  #- colon
  #- control_statement
  - file_length
  - force_cast
  - function_body_length
  #- leading_whitespace
  - line_length
  #- nesting
  #- operator_whitespace
  #- return_arrow_whitespace
  #- todo
  #- trailing_newline
  - trailing_whitespace
  - type_body_length
  #- type_name
  #- variable_name
