//
//  RetroArchCoreOptionsFileHelper.swift
//  PVRetroArch
//
//  Helper class for managing RetroArch per-game .opt files
//  Part of issue #2735: Per-Game .opt File Routing for RA Cores
//

import Foundation
import PVLogging

/// Helper class for reading and writing RetroArch .opt files
///
/// RetroArch uses .opt files for per-game and per-core core options:
/// - Per-core global: `<config_dir>/<core_name>/<core_name>.opt`
/// - Per-game override: `<config_dir>/<core_name>/<game_name>.opt`
///
/// This helper provides methods to read and write these files for Provenance UI integration.
@objc public class RetroArchCoreOptionsFileHelper: NSObject {

    /// Returns the path to the per-game .opt file for a given game
    ///
    /// - Parameters:
    ///   - gameFilename: The filename of the game (ROM name without path)
    ///   - coreBridge: The RetroArch core bridge instance
    /// - Returns: The path to the .opt file, or nil if the path cannot be determined
    @objc public static func perGameOptionsPath(forGameFilename gameFilename: String,
                                                coreBridge: PVRetroArchCoreBridge) -> String? {
        return PVRetroArchCoreBridge.perGameOptionsPath(forGame: gameFilename)
    }

    /// Returns the path to the per-core global .opt file
    ///
    /// - Parameter coreBridge: The RetroArch core bridge instance
    /// - Returns: The path to the core's global .opt file, or nil if the path cannot be determined
    @objc public static func perCoreOptionsPath(coreBridge: PVRetroArchCoreBridge) -> String? {
        return PVRetroArchCoreBridge.perCoreOptionsPath()
    }

    /// Reads the contents of an .opt file
    ///
    /// - Parameter path: Path to the .opt file
    /// - Returns: Dictionary of option key-value pairs, or nil if the file doesn't exist or can't be read
    @objc public static func readOptFile(atPath path: String) -> [String: String]? {
        guard FileManager.default.fileExists(atPath: path) else {
            DLOG("[RetroArchCoreOptionsFileHelper] .opt file does not exist at path: \(path)")
            return nil
        }

        guard let contents = try? String(contentsOfFile: path, encoding: .utf8) else {
            ELOG("[RetroArchCoreOptionsFileHelper] Failed to read .opt file at path: \(path)")
            return nil
        }

        var options: [String: String] = [:]
        let lines = contents.components(separatedBy: .newlines)

        for line in lines {
            let trimmedLine = line.trimmingCharacters(in: .whitespacesAndNewlines)

            // Skip empty lines and comments
            guard !trimmedLine.isEmpty, !trimmedLine.hasPrefix("#") else {
                continue
            }

            // Parse key = "value" format
            // RetroArch .opt files use format: option_key = "option_value"
            if let equalRange = trimmedLine.range(of: "=") {
                let key = String(trimmedLine[..<equalRange.lowerBound]).trimmingCharacters(in: .whitespaces)
                var value = String(trimmedLine[equalRange.upperBound...]).trimmingCharacters(in: .whitespaces)

                // Remove quotes if present
                if value.hasPrefix("\"") && value.hasSuffix("\"") {
                    value = String(value.dropFirst().dropLast())
                }

                options[key] = value
            }
        }

        ILOG("[RetroArchCoreOptionsFileHelper] Read \(options.count) options from .opt file: \(path)")
        return options
    }

    /// Writes option key-value pairs to an .opt file
    ///
    /// - Parameters:
    ///   - options: Dictionary of option key-value pairs
    ///   - path: Path to the .opt file
    /// - Returns: True if the file was written successfully, false otherwise
    @discardableResult
    @objc public static func writeOptFile(options: [String: String], toPath path: String) -> Bool {
        // Ensure the parent directory exists
        let parentDir = (path as NSString).deletingLastPathComponent
        do {
            try FileManager.default.createDirectory(atPath: parentDir,
                                                    withIntermediateDirectories: true,
                                                    attributes: nil)
        } catch {
            ELOG("[RetroArchCoreOptionsFileHelper] Failed to create directory at path: \(parentDir), error: \(error)")
            return false
        }

        // Build the file content
        var lines: [String] = []
        lines.append("# RetroArch Core Options")
        lines.append("# Generated by Provenance")
        lines.append("")

        // Sort keys for consistent output
        let sortedKeys = options.keys.sorted()
        for key in sortedKeys {
            if let value = options[key] {
                // Escape quotes in value if necessary
                let escapedValue = value.replacingOccurrences(of: "\"", with: "\\\"")
                lines.append("\(key) = \"\(escapedValue)\"")
            }
        }

        let content = lines.joined(separator: "\n")

        do {
            try content.write(toFile: path, atomically: true, encoding: .utf8)
            ILOG("[RetroArchCoreOptionsFileHelper] Wrote \(options.count) options to .opt file: \(path)")
            return true
        } catch {
            ELOG("[RetroArchCoreOptionsFileHelper] Failed to write .opt file at path: \(path), error: \(error)")
            return false
        }
    }

    /// Merges new options into an existing .opt file, preserving existing values not in the new set
    ///
    /// - Parameters:
    ///   - newOptions: Dictionary of new option key-value pairs
    ///   - path: Path to the .opt file
    /// - Returns: True if the merge was successful, false otherwise
    @discardableResult
    @objc public static func mergeOptions(_ newOptions: [String: String], intoOptFileAtPath path: String) -> Bool {
        var existingOptions = readOptFile(atPath: path) ?? [:]

        // Merge new options into existing
        for (key, value) in newOptions {
            existingOptions[key] = value
        }

        return writeOptFile(options: existingOptions, toPath: path)
    }

    /// Deletes an .opt file
    ///
    /// - Parameter path: Path to the .opt file
    /// - Returns: True if the file was deleted or didn't exist, false if deletion failed
    @discardableResult
    @objc public static func deleteOptFile(atPath path: String) -> Bool {
        guard FileManager.default.fileExists(atPath: path) else {
            return true
        }

        do {
            try FileManager.default.removeItem(atPath: path)
            ILOG("[RetroArchCoreOptionsFileHelper] Deleted .opt file: \(path)")
            return true
        } catch {
            ELOG("[RetroArchCoreOptionsFileHelper] Failed to delete .opt file at path: \(path), error: \(error)")
            return false
        }
    }

    /// Returns a list of all game-specific .opt files for a given core
    ///
    /// - Parameters:
    ///   - coreName: The library name of the core
    ///   - configDirectory: The RetroArch config directory path
    /// - Returns: Array of paths to .opt files, or empty array if none found
    @objc public static func allGameSpecificOptFiles(forCoreName coreName: String,
                                                      configDirectory: String) -> [String] {
        let coreConfigDir = (configDirectory as NSString).appendingPathComponent(coreName)
        let coreOptFile = (coreConfigDir as NSString).appendingPathComponent("\(coreName).opt")

        guard let files = try? FileManager.default.contentsOfDirectory(atPath: coreConfigDir) else {
            return []
        }

        // Filter for .opt files that are not the core's global .opt file
        return files
            .filter { $0.hasSuffix(".opt") && $0 != "\(coreName).opt" }
            .map { (coreConfigDir as NSString).appendingPathComponent($0) }
    }
}

// MARK: - Swift Extensions

public extension RetroArchCoreOptionsFileHelper {

    /// Swift-friendly version of readOptFile that returns a non-optional dictionary
    ///
    /// - Parameter path: Path to the .opt file
    /// - Returns: Dictionary of option key-value pairs (empty if file doesn't exist)
    static func readOptions(fromPath path: String) -> [String: String] {
        return readOptFile(atPath: path) ?? [:]
    }

    /// Checks if a per-game .opt file exists for the given game
    ///
    /// - Parameters:
    ///   - gameFilename: The filename of the game (ROM name without path)
    ///   - coreBridge: The RetroArch core bridge instance
    /// - Returns: True if the per-game .opt file exists
    static func perGameOptionsExist(forGameFilename gameFilename: String,
                                     coreBridge: PVRetroArchCoreBridge) -> Bool {
        guard let path = perGameOptionsPath(forGameFilename: gameFilename, coreBridge: coreBridge) else {
            return false
        }
        return FileManager.default.fileExists(atPath: path)
    }
}
