# CMake generated Testfile for 
# Source directory: /Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common
# Build directory: /Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Source/UnitTests/Common
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(BitFieldTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/BitFieldTest.app/BitFieldTest")
  set_tests_properties(BitFieldTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;1;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(BitFieldTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/BitFieldTest.app/BitFieldTest")
  set_tests_properties(BitFieldTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;1;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(BitFieldTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/BitFieldTest.app/BitFieldTest")
  set_tests_properties(BitFieldTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;1;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(BitFieldTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/BitFieldTest.app/BitFieldTest")
  set_tests_properties(BitFieldTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;1;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(BitFieldTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(BitSetTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/BitSetTest.app/BitSetTest")
  set_tests_properties(BitSetTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;2;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(BitSetTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/BitSetTest.app/BitSetTest")
  set_tests_properties(BitSetTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;2;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(BitSetTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/BitSetTest.app/BitSetTest")
  set_tests_properties(BitSetTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;2;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(BitSetTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/BitSetTest.app/BitSetTest")
  set_tests_properties(BitSetTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;2;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(BitSetTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(BitUtilsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/BitUtilsTest.app/BitUtilsTest")
  set_tests_properties(BitUtilsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;3;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(BitUtilsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/BitUtilsTest.app/BitUtilsTest")
  set_tests_properties(BitUtilsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;3;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(BitUtilsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/BitUtilsTest.app/BitUtilsTest")
  set_tests_properties(BitUtilsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;3;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(BitUtilsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/BitUtilsTest.app/BitUtilsTest")
  set_tests_properties(BitUtilsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;3;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(BitUtilsTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(BlockingLoopTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/BlockingLoopTest.app/BlockingLoopTest")
  set_tests_properties(BlockingLoopTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;4;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(BlockingLoopTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/BlockingLoopTest.app/BlockingLoopTest")
  set_tests_properties(BlockingLoopTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;4;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(BlockingLoopTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/BlockingLoopTest.app/BlockingLoopTest")
  set_tests_properties(BlockingLoopTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;4;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(BlockingLoopTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/BlockingLoopTest.app/BlockingLoopTest")
  set_tests_properties(BlockingLoopTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;4;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(BlockingLoopTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(BusyLoopTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/BusyLoopTest.app/BusyLoopTest")
  set_tests_properties(BusyLoopTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;5;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(BusyLoopTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/BusyLoopTest.app/BusyLoopTest")
  set_tests_properties(BusyLoopTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;5;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(BusyLoopTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/BusyLoopTest.app/BusyLoopTest")
  set_tests_properties(BusyLoopTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;5;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(BusyLoopTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/BusyLoopTest.app/BusyLoopTest")
  set_tests_properties(BusyLoopTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;5;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(BusyLoopTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CommonFuncsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/CommonFuncsTest.app/CommonFuncsTest")
  set_tests_properties(CommonFuncsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;6;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CommonFuncsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/CommonFuncsTest.app/CommonFuncsTest")
  set_tests_properties(CommonFuncsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;6;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CommonFuncsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/CommonFuncsTest.app/CommonFuncsTest")
  set_tests_properties(CommonFuncsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;6;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CommonFuncsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/CommonFuncsTest.app/CommonFuncsTest")
  set_tests_properties(CommonFuncsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;6;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(CommonFuncsTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CryptoEcTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/CryptoEcTest.app/CryptoEcTest")
  set_tests_properties(CryptoEcTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;7;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CryptoEcTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/CryptoEcTest.app/CryptoEcTest")
  set_tests_properties(CryptoEcTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;7;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CryptoEcTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/CryptoEcTest.app/CryptoEcTest")
  set_tests_properties(CryptoEcTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;7;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CryptoEcTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/CryptoEcTest.app/CryptoEcTest")
  set_tests_properties(CryptoEcTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;7;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(CryptoEcTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EnumFormatterTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/EnumFormatterTest.app/EnumFormatterTest")
  set_tests_properties(EnumFormatterTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;8;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EnumFormatterTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/EnumFormatterTest.app/EnumFormatterTest")
  set_tests_properties(EnumFormatterTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;8;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EnumFormatterTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/EnumFormatterTest.app/EnumFormatterTest")
  set_tests_properties(EnumFormatterTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;8;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EnumFormatterTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/EnumFormatterTest.app/EnumFormatterTest")
  set_tests_properties(EnumFormatterTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;8;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(EnumFormatterTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EventTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/EventTest.app/EventTest")
  set_tests_properties(EventTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;9;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EventTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/EventTest.app/EventTest")
  set_tests_properties(EventTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;9;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EventTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/EventTest.app/EventTest")
  set_tests_properties(EventTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;9;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EventTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/EventTest.app/EventTest")
  set_tests_properties(EventTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;9;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(EventTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(FileUtilTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/FileUtilTest.app/FileUtilTest")
  set_tests_properties(FileUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;10;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(FileUtilTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/FileUtilTest.app/FileUtilTest")
  set_tests_properties(FileUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;10;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(FileUtilTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/FileUtilTest.app/FileUtilTest")
  set_tests_properties(FileUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;10;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(FileUtilTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/FileUtilTest.app/FileUtilTest")
  set_tests_properties(FileUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;10;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(FileUtilTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(FixedSizeQueueTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/FixedSizeQueueTest.app/FixedSizeQueueTest")
  set_tests_properties(FixedSizeQueueTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;11;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(FixedSizeQueueTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/FixedSizeQueueTest.app/FixedSizeQueueTest")
  set_tests_properties(FixedSizeQueueTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;11;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(FixedSizeQueueTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/FixedSizeQueueTest.app/FixedSizeQueueTest")
  set_tests_properties(FixedSizeQueueTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;11;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(FixedSizeQueueTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/FixedSizeQueueTest.app/FixedSizeQueueTest")
  set_tests_properties(FixedSizeQueueTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;11;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(FixedSizeQueueTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(FlagTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/FlagTest.app/FlagTest")
  set_tests_properties(FlagTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;12;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(FlagTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/FlagTest.app/FlagTest")
  set_tests_properties(FlagTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;12;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(FlagTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/FlagTest.app/FlagTest")
  set_tests_properties(FlagTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;12;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(FlagTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/FlagTest.app/FlagTest")
  set_tests_properties(FlagTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;12;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(FlagTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(FloatUtilsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/FloatUtilsTest.app/FloatUtilsTest")
  set_tests_properties(FloatUtilsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;13;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(FloatUtilsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/FloatUtilsTest.app/FloatUtilsTest")
  set_tests_properties(FloatUtilsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;13;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(FloatUtilsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/FloatUtilsTest.app/FloatUtilsTest")
  set_tests_properties(FloatUtilsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;13;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(FloatUtilsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/FloatUtilsTest.app/FloatUtilsTest")
  set_tests_properties(FloatUtilsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;13;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(FloatUtilsTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(MathUtilTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/MathUtilTest.app/MathUtilTest")
  set_tests_properties(MathUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;14;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(MathUtilTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/MathUtilTest.app/MathUtilTest")
  set_tests_properties(MathUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;14;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(MathUtilTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/MathUtilTest.app/MathUtilTest")
  set_tests_properties(MathUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;14;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(MathUtilTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/MathUtilTest.app/MathUtilTest")
  set_tests_properties(MathUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;14;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(MathUtilTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NandPathsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/NandPathsTest.app/NandPathsTest")
  set_tests_properties(NandPathsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;15;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NandPathsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/NandPathsTest.app/NandPathsTest")
  set_tests_properties(NandPathsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;15;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NandPathsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/NandPathsTest.app/NandPathsTest")
  set_tests_properties(NandPathsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;15;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NandPathsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/NandPathsTest.app/NandPathsTest")
  set_tests_properties(NandPathsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;15;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(NandPathsTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SPSCQueueTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/SPSCQueueTest.app/SPSCQueueTest")
  set_tests_properties(SPSCQueueTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;16;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SPSCQueueTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/SPSCQueueTest.app/SPSCQueueTest")
  set_tests_properties(SPSCQueueTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;16;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(SPSCQueueTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/SPSCQueueTest.app/SPSCQueueTest")
  set_tests_properties(SPSCQueueTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;16;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SPSCQueueTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/SPSCQueueTest.app/SPSCQueueTest")
  set_tests_properties(SPSCQueueTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;16;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(SPSCQueueTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(StringUtilTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/StringUtilTest.app/StringUtilTest")
  set_tests_properties(StringUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;17;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(StringUtilTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/StringUtilTest.app/StringUtilTest")
  set_tests_properties(StringUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;17;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(StringUtilTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/StringUtilTest.app/StringUtilTest")
  set_tests_properties(StringUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;17;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(StringUtilTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/StringUtilTest.app/StringUtilTest")
  set_tests_properties(StringUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;17;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(StringUtilTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SwapTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/SwapTest.app/SwapTest")
  set_tests_properties(SwapTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;18;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SwapTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/SwapTest.app/SwapTest")
  set_tests_properties(SwapTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;18;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(SwapTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/SwapTest.app/SwapTest")
  set_tests_properties(SwapTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;18;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SwapTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/SwapTest.app/SwapTest")
  set_tests_properties(SwapTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;18;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Common/CMakeLists.txt;0;")
else()
  add_test(SwapTest NOT_AVAILABLE)
endif()
