//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ProSystem.rc
//
#define IDS_ZIP1                        1
#define IDS_ZIP2                        2
#define IDS_ZIP3                        3
#define IDS_ZIP5                        5
#define IDS_ZIP6                        6
#define IDS_ZIP8                        8
#define IDS_ZIP9                        9
#define IDS_ZIP10                       10
#define IDS_ZIP11                       11
#define IDS_ZIP12                       12
#define IDS_BIOS1                       13
#define IDS_BIOS2                       14
#define IDS_BIOS3                       15
#define IDS_BIOS4                       16
#define IDS_BIOS5                       17
#define IDS_BIOS6                       18
#define IDS_CARTRIDGE1                  19
#define IDS_CARTRIDGE2                  20
#define IDS_CARTRIDGE3                  21
#define IDS_CARTRIDGE4                  22
#define IDS_CARTRIDGE5                  23
#define IDS_CARTRIDGE6                  24
#define IDS_CARTRIDGE7                  25
#define IDS_PALETTE1                    26
#define IDS_PALETTE2                    27
#define IDS_PALETTE3                    28
#define IDS_PALETTE4                    29
#define IDS_PROSYSTEM1                  30
#define IDS_PROSYSTEM2                  31
#define IDS_PROSYSTEM3                  32
#define IDS_PROSYSTEM4                  33
#define IDS_PROSYSTEM5                  34
#define IDS_PROSYSTEM6                  35
#define IDS_PROSYSTEM7                  36
#define IDS_PROSYSTEM8                  37
#define IDS_PROSYSTEM9                  38
#define IDS_PROSYSTEM10                 39
#define IDS_PROSYSTEM11                 40
#define IDS_PROSYSTEM12                 41
#define IDS_PROSYSTEM13                 42
#define IDS_PROSYSTEM14                 43
#define IDS_PROSYSTEM15                 44
#define IDS_CONSOLE1                    45
#define IDS_CONSOLE2                    46
#define IDS_CONSOLE3                    47
#define IDS_CONSOLE4                    48
#define IDS_CONSOLE5                    49
#define IDS_CONSOLE6                    50
#define IDS_CONSOLE7                    51
#define IDS_DATABASE1                   52
#define IDS_DATABASE2                   53
#define IDS_DISPLAY1                    54
#define IDS_DISPLAY2                    55
#define IDS_DISPLAY3                    56
#define IDS_DISPLAY4                    57
#define IDS_DISPLAY5                    58
#define IDS_DISPLAY6                    59
#define IDS_DISPLAY7                    60
#define IDS_DISPLAY8                    61
#define IDS_DISPLAY9                    62
#define IDS_DISPLAY10                   63
#define IDS_DISPLAY11                   64
#define IDS_DISPLAY12                   65
#define IDS_DISPLAY13                   66
#define IDS_DISPLAY14                   67
#define IDS_DISPLAY15                   68
#define IDS_DISPLAY16                   69
#define IDS_DISPLAY17                   70
#define IDS_DISPLAY18                   71
#define IDS_DISPLAY19                   72
#define IDS_DISPLAY20                   73
#define IDS_DISPLAY21                   74
#define IDS_DISPLAY22                   75
#define IDS_DISPLAY23                   76
#define IDS_DISPLAY24                   77
#define IDS_DISPLAY25                   78
#define IDS_DISPLAY26                   79
#define IDS_DISPLAY27                   80
#define IDS_DISPLAY28                   81
#define IDS_DISPLAY29                   82
#define IDS_DISPLAY30                   83
#define IDS_DISPLAY31                   84
#define IDS_DISPLAY32                   85
#define IDS_DISPLAY33                   86
#define IDS_INPUT1                      87
#define IDS_INPUT2                      88
#define IDS_INPUT3                      89
#define IDS_INPUT4                      90
#define IDS_INPUT5                      91
#define IDS_INPUT6                      92
#define IDS_INPUT7                      93
#define IDS_INPUT8                      94
#define IDS_INPUT9                      95
#define IDS_INPUT10                     96
#define IDS_INPUT11                     97
#define IDS_INPUT12                     98
#define IDS_MENU1                       99
#define IDS_MENU2                       100
#define IDR_MAINMENU                    101
#define IDD_DIALOG_ABOUT                101
#define IDR_MENU_MAIN                   101
#define IDS_MENU3                       101
#define IDR_ACCELERATOR                 102
#define IDD_DIALOG_CONTROLLER           102
#define IDS_MENU4                       102
#define IDD_DIALOG_CONSOLE              103
#define IDS_MENU5                       103
#define IDS_MENU6                       104
#define IDS_MENU7                       105
#define IDS_MENU8                       106
#define IDS_MENU9                       107
#define IDS_MENU10                      108
#define IDS_MENU11                      109
#define IDS_MENU12                      110
#define IDI_ICON_PROSYSTEM              111
#define IDS_MENU13                      111
#define IDS_MENU14                      112
#define IDS_MENU15                      113
#define IDD_DIALOG_USER                 114
#define IDS_MENU16                      114
#define IDS_SOUND1                      115
#define IDS_SOUND2                      116
#define IDS_SOUND3                      117
#define IDS_SOUND4                      118
#define IDS_SOUND5                      119
#define IDS_SOUND6                      120
#define IDS_SOUND7                      121
#define IDS_SOUND8                      122
#define IDS_SOUND9                      123
#define IDS_SOUND10                     124
#define IDS_SOUND11                     125
#define IDS_SOUND12                     126
#define IDS_SOUND13                     127
#define IDS_SOUND14                     128
#define IDS_SOUND15                     129
#define IDS_SOUND16                     130
#define IDS_STRING132                   132
#define IDS_CARTRIDGE8                  133
#define IDS_CARTRIDGE9                  134
#define IDC_BUTTON_ABOUT_OK             1170
#define IDC_BUTTON_CONTROLLER_OK        1175
#define IDC_COMBO_CONTROLLER_UP         1176
#define IDC_COMBO_CONTROLLER_DOWN       1177
#define IDC_COMBO_CONTROLLER_LEFT       1178
#define IDC_COMBO_PART_MENU             1178
#define IDC_COMBO_CONTROLLER_RIGHT      1179
#define IDC_COMBO_PART_EXIT             1179
#define IDC_COMBO_CONTROLLER_BUTTON1    1180
#define IDC_COMBO_CONSOLE_RESET         1181
#define IDC_COMBO_DEVICE_UP             1181
#define IDC_COMBO_CONSOLE_SELECT        1182
#define IDC_COMBO_DEVICE_DOWN           1182
#define IDC_COMBO_CONSOLE_PAUSE         1183
#define IDC_COMBO_DEVICE_LEFT           1183
#define IDC_COMBO_CONSOLE_RIGHT         1184
#define IDC_COMBO_DEVICE_RIGHT          1184
#define IDC_COMBO_CONSOLE_LEFT          1185
#define IDC_COMBO_DEVICE_BUTTON1        1185
#define IDC_COMBO_CONTROLLER_BUTTON2    1186
#define IDC_BUTTON_CONSOLE_OK           1186
#define IDC_BUTTON_CONTROLLER_CANCEL    1187
#define IDC_COMBO_DEVICE_RESET          1187
#define IDC_BUTTON_CONSOLE_CANCEL       1188
#define IDC_COMBO_DEVICE_BUTTON2        1188
#define IDC_COMBO_DEVICE_SELECT         1189
#define IDC_COMBO_DEVICE_PAUSE          1190
#define IDC_COMBO_DEVICE_MENU           1190
#define IDC_STATIC_VERSION2             1190
#define IDC_COMBO_DEVICE_RIGHTD         1191
#define IDC_COMBO_DEVICE_EXIT           1191
#define IDC_STATIC_VERSION3             1191
#define IDC_COMBO_DEVICE_LEFTD          1192
#define IDC_COMBO_MOD_MENU              1192
#define IDC_COMBO_MOD_EXIT              1193
#define IDC_BUTTON_USER_OK              1194
#define IDC_BUTTON_USER_CANCEL          1195
#define IDM_RECENT_SLOT0                30000
#define IDM_RECENT_SLOT1                30001
#define IDM_RECENT_SLOT2                30002
#define IDM_RECENT_SLOT3                30003
#define IDM_RECENT_SLOT4                30004
#define IDM_RECENT_SLOT5                30005
#define IDM_RECENT_SLOT6                30006
#define IDM_RECENT_SLOT7                30007
#define IDM_RECENT_SLOT8                30008
#define IDM_RECENT_SLOT9                30009
#define IDM_FILE_OPEN                   40001
#define IDM_FILE_CLOSE                  40007
#define IDM_SAVE_SAVEAS                 40008
#define IDM_LOAD_LOADFROM               40015
#define IDM_FILE_EXIT                   40021
#define IDM_OPTIONS_RESET               40022
#define IDM_OPTIONS_PAUSE               40023
#define IDM_DISPLAY_FULLSCREEN          40024
#define IDM_DISPLAY_ZOOM1               40025
#define IDM_DISPLAY_ZOOM2               40026
#define IDM_DISPLAY_ZOOM3               40027
#define IDM_DISPLAY_ZOOM4               40028
#define IDM_OPTIONS_MENU                40039
#define IDM_HELP_ABOUT                  40040
#define IDM_OPTIONS_SETTINGS            40062
#define IDM_SAVE_NEXT                   40094
#define IDM_DISPLAY_SCREENSHOT          40099
#define IDM_DISPLAY_STRETCHED           40101
#define IDM_SAMPLERATE_11025            40107
#define IDM_SAMPLERATE_22050            40108
#define IDM_SAMPLERATE_31440            40109
#define IDM_SAMPLERATE_44100            40110
#define IDM_SAMPLERATE_48000            40111
#define IDM_SAMPLERATE_96000            40112
#define IDM_LATENCY_NONE                40113
#define IDM_LATENCY_VERYLOW             40114
#define IDM_LATENCY_LOW                 40115
#define IDM_LATENCY_MEDIUM              40116
#define IDM_LATENCY_HIGH                40117
#define IDM_LATENCY_VERYHIGH            40118
#define IDM_BLANK                       40144
#define IDM_FRAMESKIP_0                 40146
#define IDM_FRAMESKIP_1                 40148
#define IDM_FRAMESKIP_5                 40160
#define IDM_FRAMESKIP_10                40161
#define IDM_FRAMESKIP_15                40162
#define IDM_FRAMESKIP_20                40163
#define IDM_FRAMESKIP_25                40164
#define IDM_FRAMESKIP_30                40165
#define IDM_FILE_SAVE                   40167
#define IDM_FILE_LOAD                   40168
#define IDM_DISPLAY_PALETTE             40169
#define IDM_MUTE_TIA                    40172
#define IDM_SOUND_POKEY                 40173
#define IDM_MUTE_ALL                    40174
#define IDM_EMULATION_BIOS              40175
#define IDM_OPTIONS_INPUT               40176
#define IDM_REGION_AUTO                 40177
#define IDM_REGION_NTSC                 40178
#define IDM_REGION_PAL                  40179
#define IDM_FRAMESKIP_2                 40181
#define IDM_FRAMESKIP_3                 40182
#define IDM_FRAMESKIP_4                 40183
#define IDM_FRAMESKIP_6                 40184
#define IDM_FRAMESKIP_7                 40185
#define IDM_FRAMESKIP_8                 40186
#define IDM_FRAMESKIP_9                 40187
#define IDM_EMULATION_DATABASE          40189
#define IDM_SOUND_MUTE                  40190
#define IDM_INPUT_CONTROLLER1           40191
#define IDM_INPUT_CONTROLLER2           40192
#define IDM_INPUT_CONSOLE               40193
#define IDM_HELP_CONTENTS               40195
#define IDM_HELP_INDEX                  40196
#define IDM_INPUT_USER                  40198
#define ID_OPTIONS_DISPLAY_SCREENSHOT_REMOVENONWEBSYMBOLS 40200
#define ID_OPTIONS_DISPLAY_SCREENSHOT_REPLACESPACESBY 40201
#define IDM_MODES_BASE                  50000
#define IDM_MODES_LAST                  51000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40202
#define _APS_NEXT_CONTROL_VALUE         1196
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
