# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jmattiello/Workspace/Provenance/Cores/Play/Play-/deps/Dependencies/build_cmake/iCade-iOS/CMakeLists.txt))

/Users/jmattiello/Workspace/Provenance/Cores/Play/cmake/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.21.1/bin/cmake -H/Users/jmattiello/Workspace/Provenance/Cores/Play/Play- -B/Users/jmattiello/Workspace/Provenance/Cores/Play/cmake
