source 'https://cdn.cocoapods.org/'

# inhibit_all_warnings!
use_frameworks!

abstract_target 'core' do

  pod 'SSZipArchive', :path => '..'

  target 'ObjectiveCExample' do
    platform :ios, '15.5'
  end

  target 'ObjectiveCExampleTests_iOS' do
    platform :ios, '15.5'
  end

  target 'ObjectiveCExampleTests_macOS' do
    platform :osx, '10.15'
  end

  target 'ObjectiveCExampleTests_tvOS' do
    platform :tvos, '15.4'
  end

  target 'SwiftExample' do
    platform :ios, '15.5'
  end
  
  target 'SwiftExample_macOS' do
    platform :osx, '10.15'
  end
  
end
