#/bin/sh -e
# Pull GIT version number to use for informational purposes

# Scripts invoked by Xcode don’t read any of the usual shell configuration files
# doing it here manually. PATH=foo:$PATH also gets ignored by XCode. 'source' seems to work fine though

if [ -f "$HOME/.profile" ] ; then
    source "$HOME/.profile"
else
    echo "No $HOME/.profile exists. PATH may not find correct version of Git if installed outside of XCode; ie. MacPorts or other build systems."
fi

PLISTBUDDY=/usr/libexec/PlistBuddy
NOW=`date`
INFOPATH="${PROJECT_DIR}/${INFOPLIST_FILE}"

###### ------------ SVN VERSION -------------------
#SVNBIN=svn
#SVNVERSIONBIN=svnversion
#
# if [ "command -v $SVNVERSIONBIN" ] ; then
#     svnrevision=`$SVNVERSIONBIN -nc ${PROJECT_DIR}| /usr/bin/sed -e 's/^[^:]*://'`
#     svnrevisionnoflags=`$SVNVERSIONBIN -nc ${PROJECT_DIR}| /usr/bin/sed -e 's/^[^:]*://;s/[A-Za-z]//'`
# else
#     echo "$SVNVERSIONBIN not found."
# fi

# if [ "command -v $SVNBIN" ] ; then
#     svndate=`LC_ALL=C $SVNBIN info ${PROJECT_DIR}| awk '/^Last Changed Date:/ {print $4,$5}'`
# else
#     echo "$SVNBIN not found."
# fi

# if [ "command -v $PLISTBUDDY" ] ; then
#     ## Read the app version (x.y.z) from the PList
#     appversion=$($PLISTBUDDY -c "Print :CFBundleShortVersionString" "${INFOPATH}")

#     ## Set the build version as the SVN revision
#     /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${svnrevisionnoflags}" ${INFOPATH}
# else
#     echo "$PLISTBUDDY not found."
# fi
if [ "command -v $PLISTBUDDY" ] ; then
    if [ "command -v ${INFOPATH}" ] ; then
        ## Read the app version (x.y.z) from the PList
        appversion=$($PLISTBUDDY -c "Print :CFBundleShortVersionString" "${INFOPATH}")
        echo "appversion=${appversion}"
    else
        error_exit "${INFOPATH} not found"
    fi
fi

function error_exit
{
    echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
    exit 1
}

######## --------------- GIT VERISON -------------------
GIT=`xcrun -find git`
if [ "command -v '$GIT'" ] ; then
    GIT_COMMIT_COUNT_RAW=`"${GIT}" rev-list --count HEAD`
    GIT_TAG=`"${GIT}" describe --tags --always --dirty`
    GIT_DATE=`"${GIT}" log -1 --format="%cd" --date="local"`
    # Use this to bump the number by X
    GIT_COMMIT_COUNT=$(($GIT_COMMIT_COUNT_RAW+0))
    echo "Commit count is $GIT_COMMIT_COUNT"
else
    error_exit "$LINENO: $GIT not found."
fi

echo "Creating Version.h in" ${PROJECT_DIR}

cat <<EOF > "${PROJECT_DIR}/Provenance/Version.h"

// Do not edit!  This file was autogenerated
//      by $0
//      on $NOW
//      user $VERSION_INFO_BUILDER
//      for build target ${TARGET_NAME}
//
// gitrevision and gitdate are as reported by git at that point in time,
// compiledate and compiletime are being filled gcc at compilation

#include <stdlib.h>

static NSString* const kAppVersion              = @"${appversion}";
static NSString* const kGITRevisionNumber       = @"${GIT_COMMIT_COUNT}";
static NSString* const kGITTag                  = @"${GIT_TAG}";
static NSString* const kGITDate                 = @"${GIT_DATE}";
static NSString* const kAppBuildConfiguration   = @"${CONFIGURATION}";

// Suppress warnings incase you choose not to use these variables
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused"

static const char* gitrevision          = "${GIT_COMMIT_COUNT}";
static const char* gittag               = "${GIT_TAG}";
static const char* gitdate              = "${GIT_DATE}";
static const char* appversion           = "${appversion}";
static const char* buildconfiguration   = "${CONFIGURATION}";
static const char* compiletime          = __TIME__;
static const char* compiledate          = __DATE__;

#pragma GCC diagnostic pop

// Diagnostic info
/*
    Info.plist path:${INFOPATH}
    PWD : ${PWD}
    XCode version ${XCODE_PRODUCT_BUILD_VERSION}
    PATH : ${PATH}
*/

EOF

##
#echo "$REV2" > ${PROJECT_DIR}/SvnRevision.txt
