#!/bin/bash -e
# Pull GIT version number to use for informational purposes
# IMPORTANT: This script uses write-if-changed to avoid touching file timestamps
# when content hasn't changed, preventing unnecessary Swift module re-planning.

# Scripts invoked by Xcode don't read any of the usual shell configuration files
# doing it here manually. PATH=foo:$PATH also gets ignored by XCode. 'source' seems to work fine though

if [ -f "$HOME/.profile" ] ; then
    source "$HOME/.profile"
fi

if [ -f "$HOME/.bash_profile" ] ; then
    source "$HOME/.bash_profile"
fi

PLISTBUDDY=/usr/libexec/PlistBuddy
INFOPATH="${PROJECT_DIR}/${INFOPLIST_FILE}"

plist_buddy_installed() {
  [-x "$(command -v "$PLISTBUDDY")"]
}

if [[ plist_buddy_installed && "${INFOPATH}" == *".plist"*  ]]; then
    if [ -f "${INFOPATH}" ]; then
        ## Read the app version (x.y.z) from the PList
        appversion=$($PLISTBUDDY -c "Print :CFBundleShortVersionString" "${INFOPATH}")
        echo "appversion=${appversion}"
    fi
fi

error_exit()
{
    echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
    exit 1
}

success_exit()
{
    echo "${PROGNAME}: ${1:-"Completed"}" 1>&2
    exit 0
}

# Write file only if content has changed (preserves timestamps for incremental builds)
write_if_changed()
{
    local target="$1"
    local content="$2"
    local tmpfile
    tmpfile=$(mktemp "${TMPDIR:-/tmp}/version.XXXXXX")
    printf '%s' "$content" > "$tmpfile"
    if [ -f "$target" ] && cmp -s "$tmpfile" "$target"; then
        rm -f "$tmpfile"
        echo "Unchanged: $target"
        return 0
    fi
    mv -f "$tmpfile" "$target"
    echo "Updated: $target"
    return 0
}

VERSION_H_PATH="${PROJECT_DIR}/Provenance/Version.h"
VERSION_SWIFT_PATH="${PROJECT_DIR}/Provenance/Version.swift"

######## --------------- GIT VERSION -------------------
GIT=$(xcrun -find git)
if [ "command -v '$GIT'" ] ; then
    GIT_COMMIT_COUNT_RAW=$("${GIT}" rev-list --count HEAD)
    GIT_TAG=$("${GIT}" describe --tags --always --dirty)
    GIT_DATE=$("${GIT}" log -1 --format="%cd" --date="local")
    GIT_BRANCH=$("${GIT}" branch | grep \* | cut -d ' ' -f2-)
    # Use this to bump the number by X
    GIT_COMMIT_COUNT=$(($GIT_COMMIT_COUNT_RAW+0))
    echo "Commit count is $GIT_COMMIT_COUNT"
else
    error_exit "$LINENO: $GIT not found."
fi

# Quick check: if the cache file matches current git state, skip entirely
vpath="$SRCROOT/.version"
cache_key="${GIT_COMMIT_COUNT}|${GIT_TAG}|${GIT_BRANCH}|${CONFIGURATION}|${appversion}"
if [[ -f "$VERSION_H_PATH" ]] && [[ -f "$VERSION_SWIFT_PATH" ]] && [[ -f "$vpath" ]] && [[ "$(< "${vpath}")" == "${cache_key}" ]]; then
    success_exit "Cache matches — no version changes"
fi

# Generate Version.h content (no timestamp in content — that caused needless rebuilds)
VERSION_H_CONTENT=$(cat <<ENDOFHEADER
// Do not edit!  This file was autogenerated by createVersionHeader.sh

#include <stdlib.h>

static NSString* const kAppVersion              = @"${appversion}";
static NSString* const kGITRevisionNumber       = @"${GIT_COMMIT_COUNT}";
static NSString* const kGITTag                  = @"${GIT_TAG}";
static NSString* const kGITDate                 = @"${GIT_DATE}";
static NSString* const kGITBranch               = @"${GIT_BRANCH}";
static NSString* const kAppBuildConfiguration   = @"${CONFIGURATION}";
static NSString* const kOrgIdentifier           = @"${ORG_IDENTIFIER}";
static NSString* const kOrgPrefix               = @"${ORG_PREFIX}";
static NSString* const kProductBundleIdentifier = @"${PRODUCT_BUNDLE_IDENTIFIER}";
static NSString* const kAppGroupIdentifier      = @"${APP_GROUP_IDENTIFIER}";
static NSString* const kiCloudContainerIdenfitier = @"${ICLOUD_CONTAINER_IDENTIFIER}";
static NSString* const kUbiquityIdentityTokenKey  = @"${PRODUCT_BUNDLE_IDENTIFIER}.UbiquityIdentityToken";

// Suppress warnings incase you choose not to use these variables
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused"

static const char* gitrevision          = "${GIT_COMMIT_COUNT}";
static const char* gittag               = "${GIT_TAG}";
static const char* gitdate              = "${GIT_DATE}";
static const char* gitbranch            = "${GIT_BRANCH}";
static const char* appversion           = "${appversion}";
static const char* buildconfiguration   = "${CONFIGURATION}";
static const char* builtByUser          = "${USER}";
static const char* kOrgIdentifier           = "${ORG_IDENTIFIER}";
static const char* kOrgPrefix               = "${ORG_PREFIX}";
static const char* kProductBundleIdentifier = "${PRODUCT_BUNDLE_IDENTIFIER}";
static const char* kAppGroupIdentifier      = "${APP_GROUP_IDENTIFIER}";
static const char* kiCloudContainerIdenfitier = "${ICLOUD_CONTAINER_IDENTIFIER}";
static const char* kUbiquityIdentityTokenKey     = "${PRODUCT_BUNDLE_IDENTIFIER}.UbiquityIdentityToken";

#pragma GCC diagnostic pop
ENDOFHEADER
)

# Generate Version.swift content (no timestamp in content)
VERSION_SWIFT_CONTENT=$(cat <<ENDOFSWIFT
// Do not edit!  This file was autogenerated by createVersionHeader.sh

public let kAppVersion : String = "${appversion}"
public let kGITRevisionNumber : String = "${GIT_COMMIT_COUNT}"
public let kGITTag : String = "${GIT_TAG}"
public let kGITDate : String = "${GIT_DATE}"
public let kGITBranch : String = "${GIT_BRANCH}"
public let kAppBuildConfiguration : String  = "${CONFIGURATION}"

public let gitrevision          = "${GIT_COMMIT_COUNT}"
public let gittag               = "${GIT_TAG}"
public let gitdate              = "${GIT_DATE}"
public let gitbranch            = "${GIT_BRANCH}"
public let appversion           = "${appversion}"
public let buildconfiguration   = "${CONFIGURATION}"
public let builtByUser          = "${USER}"
public let kOrgIdentifier               = "${ORG_IDENTIFIER}"
public let kOrgPrefix                   = "${ORG_PREFIX}"
public let kProductBundleIdentifier     = "${PRODUCT_BUNDLE_IDENTIFIER}"
public let kAppGroupIdentifier          = "${APP_GROUP_IDENTIFIER}"
public let kiCloudContainerIdenfitier   = "${ICLOUD_CONTAINER_IDENTIFIER}"
public let kUbiquityIdentityTokenKey     = "${PRODUCT_BUNDLE_IDENTIFIER}.UbiquityIdentityToken"
ENDOFSWIFT
)

# Only write files if content actually changed
write_if_changed "$VERSION_H_PATH" "$VERSION_H_CONTENT"
write_if_changed "$VERSION_SWIFT_PATH" "$VERSION_SWIFT_CONTENT"

# Update cache key so next build skips early
echo "$cache_key" > "$vpath"
