language: objective-c
cache: cocoapods
rvm: 2.2.2
osx_image: xcode8

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=SwiftyUserDefaults.xcodeproj

before_install:
  - gem install cocoapods -v 1.1.0.rc2 # remove -v after it ships
  - gem install xcpretty

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  
  - xcodebuild -project "$PROJECT" -scheme 'SwiftyUserDefaults' -destination 'name=iPhone 6,OS=10.0' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build | xcpretty
  - xcodebuild -project "$PROJECT" -scheme 'SwiftyUserDefaults tvOS' -sdk appletvsimulator10.0 -destination 'name=Apple TV 1080p' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build | xcpretty
  - xcodebuild -project "$PROJECT" -scheme 'SwiftyUserDefaults watchOS' -sdk iphonesimulator -destination 'name=Apple Watch - 42mm' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build | xcpretty
  - xcodebuild -project "$PROJECT" -scheme 'SwiftyUserDefaults Mac' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build | xcpretty
  
  - xcodebuild -project "$PROJECT" -scheme 'SwiftyUserDefaults' -sdk iphonesimulator -destination 'name=iPhone 6,OS=10.0' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty
  - xcodebuild -project "$PROJECT" -scheme 'SwiftyUserDefaults tvOS' -sdk appletvsimulator10.0 -destination 'name=Apple TV 1080p' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty
  - xcodebuild -project "$PROJECT" -scheme 'SwiftyUserDefaults Mac' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty
  
  - pod _1.1.0.rc2_ lib lint
