my_list =  Split("""
adler32.c
compress.c
crc32.c
deflate.c
gzio.c
infblock.c
infcodes.c
inffast.c
inflate.c
inftrees.c
infutil.c
trees.c
uncompr.c
zutil.c 
""")

for x in range(len(my_list)):
  my_list[x] = 'drivers/win/zlib/' + my_list[x]
Return('my_list')
