

#ifndef _NETPLAY_H
#define _NETPLAY_H

#define NETPLAY_VERSION 0x100

typedef enum
{
    NETPLAY_GAMESTATE_IDLE,
    NETPLAY_GAMESTATE_LOADING,
    NETPLAY_GAMESTATE_LOADED,
    NETPLAY_GAMESTATE_LOADERROR,
    NETPLAY_GAMESTATE_UNLOAD,

    NETPLAY_GAMESTATE_PLAY,
    NETPLAY_GAMESTATE_PAUSE,

} NetPlayGameStateE;

typedef enum
{
	NETPLAY_STATUS_IDLE,
	NETPLAY_STATUS_CONNECTING,
	NETPLAY_STATUS_CONNECTED
} NetPlayStatusE;


typedef enum
{
	NETPLAY_CALLBACK_NONE,
	NETPLAY_CALLBACK_CONNECTED,
	NETPLAY_CALLBACK_DISCONNECTED,
	NETPLAY_CALLBACK_LOADGAME,
	NETPLAY_CALLBACK_UNLOADGAME,
	NETPLAY_CALLBACK_STARTGAME,
	NETPLAY_CALLBACK_TEXTMSG,
} NetPlayCallbackE;

typedef enum
{
    NETPLAY_LOADACK_OK,
    NETPLAY_LOADACK_ERROR,
    NETPLAY_LOADACK_NOTFOUND,
    NETPLAY_LOADACK_CHECKSUM,
} NetPlayLoadAckE;
  
#endif
