# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../libretro_ppsspp/ext/glslang/CHANGES.md))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../libretro_ppsspp/ext/glslang/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../libretro_ppsspp/ext/glslang/External/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../libretro_ppsspp/ext/glslang/OGLCompilersDLL/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../libretro_ppsspp/ext/glslang/SPIRV/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../libretro_ppsspp/ext/glslang/build_info.h.tmpl))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../libretro_ppsspp/ext/glslang/glslang/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../libretro_ppsspp/ext/glslang/glslang/OSDependent/Unix/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../libretro_ppsspp/ext/glslang/gtests/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../libretro_ppsspp/ext/glslang/hlsl/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../libretro_ppsspp/ext/glslang/parse_version.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/CTest.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/CTestTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/CTestUseLaunchers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/DartConfiguration.tcl.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPythonInterp.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../cmake/CMakeFiles/cmake.verify_globs))

.NOTPARALLEL:

.PHONY: all VERIFY_GLOBS

all: VERIFY_GLOBS ../cmake/CMakeFiles/cmake.check_cache

VERIFY_GLOBS:
	/usr/local/Cellar/cmake/3.26.4/bin/cmake -P ../cmake/CMakeFiles/VerifyGlobs.cmake

../cmake/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.26.4/bin/cmake -H../libretro_ppsspp -B../cmake
