# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../ppsspp/ext/glslang/CHANGES.md))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../ppsspp/ext/glslang/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../ppsspp/ext/glslang/External/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../ppsspp/ext/glslang/OGLCompilersDLL/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../ppsspp/ext/glslang/SPIRV/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../ppsspp/ext/glslang/build_info.h.tmpl))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../ppsspp/ext/glslang/glslang/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../ppsspp/ext/glslang/glslang/OSDependent/Unix/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../ppsspp/ext/glslang/gtests/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../ppsspp/ext/glslang/hlsl/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../ppsspp/ext/glslang/parse_version.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/CTest.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/CTestTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/CTestUseLaunchers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/DartConfiguration.tcl.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/FindPythonInterp.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/GNUInstallDirs.cmake))

../cmake/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/lib/python3.10/site-packages/cmake/data/bin/cmake -H../ppsspp -B../cmake
