//
//  CorePlist.swift
//
//
//  Created by Joseph Mattiello on 6/21/24.
//

import Foundation
import PVCoreBridge
import PVLogging

fileprivate let PVTGBDualCoreBundle: Bundle = Bundle.module
fileprivate let ThisBundle: Bundle = { Bundle.module }()

fileprivate let CorePlistPath: URL = PVTGBDualCoreBundle.url(forResource: "Core", withExtension: "plist")!

extension PVTGBDualCore: EmulatorCoreInfoPlistProvider {

    public static var resourceBundle: Bundle { Bundle.module }

    public static var corePlistFromBundle: EmulatorCoreInfoPlist {
        guard let plistPath = resourceBundle.url(forResource: "Core", withExtension: "plist") else {
            fatalError("Could not locate Core.plist")
        }

        guard let plistObject = NSData.init(contentsOf: plistPath) as? [String:Any] else  {
            fatalError("Could not read Core.plist")
        }

        guard let corePlist = EmulatorCoreInfoPlist.init(fromInfoDictionary: plistObject) else {
            fatalError("Could not generate EmulatorCoreInfoPlist from Core.plist")
        }

        return corePlist
    }

    /// Note: CorePlist is an enum generated by SwiftGen with a custom stencil
    /// Change the swiftgen config to the local path to see the outputs and tweak
    @objc(corePlist)
    public static var corePlist: EmulatorCoreInfoPlist { CorePlist.corePlist }

    @objc
    public var corePlist: EmulatorCoreInfoPlist { Self.corePlist }
}
