UNZIPOBJS = zlib/unzip.o
ZLIBOBJS = zlib/adler32.o zlib/compress.o zlib/crc32.o zlib/gzio.o zlib/uncompr.o zlib/deflate.o zlib/trees.o \
		zlib/zutil.o zlib/inflate.o zlib/infblock.o zlib/inftrees.o zlib/infcodes.o zlib/infutil.o zlib/inffast.o

# DO NOT DELETE THIS LINE -- make depend depends on it.

zlib/adler32.o: zlib/zlib.h zlib/zconf.h
zlib/compress.o: zlib/zlib.h zlib/zconf.h
zlib/crc32.o: zlib/zlib.h zlib/zconf.h
zlib/deflate.o: zlib/deflate.h zlib/zutil.h zlib/zlib.h zlib/zconf.h
zlib/example.o: zlib/zlib.h zlib/zconf.h
zlib/gzio.o: zlib/zutil.h zlib/zlib.h zlib/zconf.h
zlib/infblock.o: zlib/infblock.h zlib/inftrees.h zlib/infcodes.h zlib/infutil.h zlib/zutil.h zlib/zlib.h zlib/zconf.h
zlib/infcodes.o: zlib/zutil.h zlib/zlib.h zlib/zconf.h
zlib/infcodes.o: zlib/inftrees.h zlib/infblock.h zlib/infcodes.h zlib/infutil.h zlib/inffast.h
zlib/inffast.o: zlib/zutil.h zlib/zlib.h zlib/zconf.h zlib/inftrees.h
zlib/inffast.o: zlib/infblock.h zlib/infcodes.h zlib/infutil.h zlib/inffast.h
zlib/inflate.o: zlib/zutil.h zlib/zlib.h zlib/zconf.h zlib/infblock.h
zlib/inftrees.o: zlib/zutil.h zlib/zlib.h zlib/zconf.h zlib/inftrees.h
zlib/infutil.o: zlib/zutil.h zlib/zlib.h zlib/zconf.h zlib/infblock.h zlib/inftrees.h zlib/infcodes.h zlib/infutil.h
zlib/trees.o: zlib/deflate.h zlib/zutil.h zlib/zlib.h zlib/zconf.h zlib/trees.h
zlib/uncompr.o: zlib/zlib.h zlib/zconf.h
zlib/zutil.o: zlib/zutil.h zlib/zlib.h zlib/zconf.h  

zlib/unzip.o: zlib/unzip.h
