use_frameworks!
inhibit_all_warnings!

target :sRetoIOS do
  platform :ios, '9.0'
  pod 'CocoaAsyncSocket', '7.6.2'
  pod 'SocketRocket', '0.5.1'
  
  target :sRetoTests do
  end
    
end

target :sRetoMac do
  platform :osx, '10.9'
  pod 'CocoaAsyncSocket', '7.6.2'
  pod 'SocketRocket', '0.5.1'
end
