# https://github.com/marketplace/actions/release-notes-preview
name: Release-Notes-Preview

on:
  pull_request:
    branches: [develop]
  issue_comment:
    types: [edited]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow --tags
      - uses: snyk/release-notes-preview@v1.6.1
        with:
          releaseBranch: master
        env:
          GITHUB_PR_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
