# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# TODO: Fix files getting deleted after - upload to my server and host them, script to let other setup their builds - script to download and resign latest build from web
# script to resign the last local archive and copy to device
# use is_ci to detect travis
# lane_context[SharedValues::IPA_OUTPUT_PATH] lane_context[SharedValues::BUILD_NUMBER] https://docs.fastlane.tools/advanced/#lane-context
# CredentialsManager https://github.com/fastlane/fastlane/tree/master/credentials_manager
# clipboard clipboard(value: lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK] || "")
# twitter https://github.com/rb-de0/fastlane-plugin-twitter
# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

REQUIRED_XCODE_VERSION = "10.0"
# Can also use .xcode-version file

default_platform(:ios)

platform :ios do

$carthage_paths = ["./"]
$dev_domain = ENV["DEV_DOMAIN"] || "com.provenance-emu"

def load_keys
  if is_ci?
    return
  end

  begin
    import("keys")
    $dev_domain = ENV["DEV_DOMAIN"]
  rescue => exception
    if UI.interactive?
      shouldSetup = UI.confirm "Fastlane enviroment is not configured. Setup now?"
      UI.message "This feature not yet implimented. Manually edit fastlane/keys using keys.template as an example."
    end
    raise exception
  end
end

def uploadToWordpress(file)
  url = URI.parse('https://www.provenance-emu.com/wp/v2/media')
  filename = File.basename(file)
  File.open(file) do |ipa|
  req = Net::HTTP::Post::Multipart.new url.path,
    "file" => UploadIO.new(ipa, "application/octet-stream", filename)
    res = Net::HTTP.start(url.host, url.port) do |http|
      http.request(req)
    end
    UI.message "Wordpress response code: #{res.code}"
  end
end

  before_all do
    git_pull(only_tags: true)
  end
  #
  # after_all do
  #   push_git_tags
  # end
  # TODO: Make keys file from this
  desc "Setup fastlane enviroment"
  lane :setup_fastlane do
    if UI.interactive?
      apple_id = UI.input "Please enter your Apple Development ID (usually e-mail address): "
      # password = UI.password "Please enter your iTunes Connect password (this is securely encrypted in your keychain. We will never access that information directly): "
      dev_domain = UI.input "Please enter your developer domain as {com,org,net}.{NAME} (ie; com.provenance-emu will be replaced with com.johnnyappleseed if you're Johnny Appleseed on iTunes connect.): "
      if UI.confirm("Do you belong to multiple development teams (usually no)")
        team_id = UI.input "Please enter your iTunes Dev portal team number:"
        itc_team_id = UI.input "Please enter your iTunes Connect team number: (You can leave blank if you don't intend to use iTunes Connect)"
      end
    end
  end

  private_lane :verify_xcode_version do
    ensure_xcode_version(version: REQUIRED_XCODE_VERSION)
  end

  desc "Build and run tests"
  lane :test do
    scan
  end

  desc "Travis building"
  lane :travis do
    if is_ci?
      setup_travis
    else
      load_keys
    end
    alpha
  end

  desc "User Builds"
  lane :userbuild do
    UI.message "Pulling git updates."
    git_pull

    UI.message "Pulling git sub-module updates."
    git_submodule_update(
      init: true,
      recursive: true
    )

    UI.message "Switching to automatic code signing."
    enable_automatic_code_signing(
      use_automatic_signing: true,
      targets: ["Provenance", "ProvenanceTV", "Spotlight", "TopShelf"],
      # TODO, only do if set since it's optional
      # team_id: ENV["DEV_TEAM_ID"]
    )

    which_app = UI.select("Select platform: ", ["iOS", "tvOS"])

    UI.message "Getting 3rd party dependencies."

    if which_app == "tvOS"
      carthage_bootstrap_tvOS
    else
      carthage_bootstrap_ios
    end

    # Git git commit count
    commits = number_of_commits(all: true).to_s
    UI.message "Setting build # to ${commits}."
    ENV["build_number"] = commits
    updatePlistForBranch

    UI.message "Making developer build for platform #{which_app}."
    if which_app == "tvOS"
      build_developer(scheme: "ProvenanceTV-Release")
    else
      build_developer(scheme: "Provenance-Release")
    end

    # Installs the ipa on the device. If no id is given, the first found iOS device will be used.
    # Works via USB or Wi-Fi. This requires ios-deploy to be installed.
    # Please have a look at ios-deploy.
    # To quickly install it, use npm -g i ios-deploy
    # https://docs.fastlane.tools/actions/install_on_device/
    # if UI.confirm("Install to device?")
    #   install_on_device
    # end

    UI.message "Resetting enviroment."
    reset_enviroment
  end

  desc "User Setup"
  desc "Work in progress"
  private_lane :user_setup do
    UI.message "This lane will help you setup Provenance for signing and build."
    #UI.success "Successfully finished processing (usually green)"
    #UI.error "Wahaha, what's going on here! (usually red)"
    #UI.important "Make sure to use Windows (usually yellow)"

    #UI.header "Inputs" # a big box

    apple_id = UI.input("What's your Apple ID login? (usually an e-mail address)")
    apple_pass = UI.password("Your password please: ") # password inputs are hidden
    dev_domain = UI.input("What's your developer domain (usually com.yourname)?\nThis will be used to generate unique App Bundle ids to your developer account.\neg; Official releases from the Provenance team use 'com.provenance'. You cannot use 'com.provenance' for your personal account, iOS Developer portal will not allow craeting signing certificates if an app already exists with that ID.")

    app_id = "#{$dev_domain}.provenance"
    spotlight_id = "#{$dev_domain}.provenance.extension.spotlight"
    topshelf_id = "#{$dev_domain}.provenance.topshelf-extension"

    if UI.confirm("Do you want to generate new app entries in your developer account??")
      produce(
        username: apple_id,
        app_identifier: app_id,
        app_name: 'Provenance',
        language: 'English',
        # sku: '123',
        # team_name: 'SunApps GmbH', # only necessary when in multiple teams

        # Optional
        # App services can be enabled during app creation
        enable_services: {
          # TODO: Setup app groups
          #app_group: "on",               # Valid values: "on", "off"
          apple_pay: "off",               # Valid values: "on", "off"
          associated_domains: "off",      # Valid values: "on", "off"
          #data_protection: "complete",   # Valid values: "complete", "unlessopen", "untilfirstauth",
          game_center: "off",             # Valid values: "on", "off"
          health_kit: "off",              # Valid values: "on", "off"
          home_kit: "off",                # Valid values: "on", "off"
          hotspot: "off",                 # Valid values: "on", "off"
          #icloud: "cloudkit",            # Valid values: "legacy", "cloudkit"
          in_app_purchase: "off",         # Valid values: "on", "off"
          inter_app_audio: "off",         # Valid values: "on", "off"
          passbook: "off",                # Valid values: "on", "off"
          multipath: "off",               # Valid values: "on", "off"
          network_extensions: "off",      # Valid values: "on", "off"
          nfc_tag_reading: "off",         # Valid values: "on", "off"
          personal_vpn: "off",            # Valid values: "on", "off"
          push_notification: "off",       # Valid values: "on", "off"
          siri_kit: "off",                # Valid values: "on", "off"
          wallet: "off",                  # Valid values: "on", "off"
          wireless_accessory: "off",      # Valid values: "on", "off"
        }
      )

    end

    UI.message "We will now try to create or update signing certificates for your developer account"
    ###### A "Dropdown" for the user
    # project = UI.select("Select your project: ", ["Test Project", "Test Workspace"])

    # UI.success("Okay #{name}, you selected '#{project}'")

    ###### To run a command use
    # FastlaneCore::CommandExecutor.execute(command: "ls",
    #                                     print_all: true,
    #                                         error: proc do |error_output|
    #                                           # handle error here
    #                                         end)

    ###### or if you just want to receive a simple value use this only if the command doesn't take long
    # diff = Helper.backticks("git diff")

    ###### fastlane "crash" because of a user error everything that is caused by the user and is not unexpected
    UI.user_error!("You don't have a project in the current directory")

    ###### an actual crash when something unexpected happened
    UI.crash!("Network timeout")

    ###### a deprecation message
    UI.deprecated("The '--key' parameter is deprecated")
  end

  desc "Updates the bundle id and app name if a beta build"
  lane :updatePlistForBranch do
    alpha = $git_branch != "master"
    if alpha
      UI.message "Setting plist values for Alpha build"
    else
      UI.message "Setting plist values for Normal build"
    end
    backup_file(path: "Provenance/Provenance-Info.plist")
    backup_file(path: "ProvenanceTV/Info.plist")
    backup_file(path: "Spotlight/Info.plist")
    backup_file(path: "TopShelf/Info.plist")

    plist_set(normal: alpha)
  end

  desc "Resets the bundle id and app name after build"
  lane :plist_reset do
    restore_file(path: "Provenance/Provenance-Info.plist")
    restore_file(path: "ProvenanceTV/Info.plist")
    restore_file(path: "Spotlight/Info.plist")
    restore_file(path: "TopShelf/Info.plist")
    # plist_set(normal: true)
  end

  private_lane :pre_build do
    #get_certificates           # invokes cert
    #get_provisioning_profile   # invokes sigh

    # Git git commit count
    ENV["build_number"] = number_of_commits(all: true).to_s

    updatePlistForBranch

    # Clean the dir for git
    # ensure_git_status_clean
    # ensure_git_in_sync

    git_submodule_update

    if is_ci?
      # certificates # Download the certs?
      setup_certificates_private

      # temporarily disable automatic code signing
      # codesign_toggle(automatic: false)

      rome_download
    end

    # carthage_bootstrap
  end

  desc "Create a build for users "
  lane :personal do
    # match(type: "appstore") # more information: https://codesigning.guide
    cert
    sigh
    gym # Build your app - more options available

    UI.success "Successfully finished building Provenace"
    # if UI.confirm("Do you want to install to a connected device now?")
    # end
  end

  desc "Install last build to device"
  lane :install do |options|
    if cached_build_available?
      UI.important 'Skipping build because a cached build is available!'
      next # skip doing the rest of this lane
    end
  end

  private_lane :cached_build_available? do |options|
    # ...
    false
  end

  desc "Provenace Team: Push a new beta build to TestFlight"
  lane :beta do
    pre_build
    build_appstore
    reset_enviroment
  end

  desc "Upload to S3"
  private_lane :s3upload do |options|

    ipa_name = options.fetch(:ipa_name, 'Provenance.ipa')
    dsym_name = options.fetch(:ipa_name, 'Provenance.app.dSYM.zip')

    build_number = ENV["build_number"]
    build_time = Time.now.strftime('%F')

    aws_s3(
      # All of these are used to make Shenzhen's `ipa distribute:s3` command
      access_key: ENV['S3_ACCESS_KEY'],               # Required from user (unless using aws_profile).
      secret_access_key: ENV['S3_SECRET_ACCESS_KEY'], # Required from user (unless using aws_profile).
      #aws_profile: ENV['AWS_PROFILE'],                 # Required from user (unless using access_key and secret_access_key)
      bucket: "provenance-builds",                       # Required from user.
      region: "us-east-1",                       # Required from user.
      #acl: ENV['S3_ACL'],                             # Optional - defaults to 'public-read'
      #server_side_encryption: ENV['S3_SERVER_SIDE_ENCRYPTION'] # Optional

      endpoint: 'http://provenance.joemattiello.com:9000', # Optional, for buckets that require a specific endpoint
      ipa: ipa_name,                             # Required (if not uploading an APK).
      dsym: dsym_name,                   # Optional is you use `ipa` to build.

      #apk: 'AppName.apk',                             # Required (if not uploading an IPA).

      app_directory: "iOS",                # Optional but nice if you want to put multiple apps in same bucket

      path: "#{CFBundleShortVersionString}/#{git_branch}/#{CFBundleVersion}/", # This is actually the default.
      #upload_metadata: true,                          # Upload version.json, plist and HTML. Set to false to skip uploading of these files.
      #version_file_name: 'app_version.json',          # Name of the file to upload to S3. Defaults to 'version.json'
      #version_template_path: 'path/to/erb'            # Path to an ERB to configure the structure of the version JSON file
    )
  end

  desc "Provenace Team: Push a new alpha build to Hockeyapp"
  lane :alpha do
    load_keys
    pre_build

    # Codesign
    # Types, appstore adhoc development enterprise

    # update_devices // development, adhoc, appstore, enterprise
    match(app_identifier: ["#{$dev_domain}.provenance", "#{$dev_domain}.provenance.extension.spotlight"], type: "adhoc", platform: "ios", readonly: true)

    # update_project_provisioning(
    #   xcodeproj: "Project.xcodeproj",
    #   profile: "./watch_app_store.mobileprovision", # optional if you use sigh
    #   target_filter: ".*WatchKit Extension.*", # matches name or type of a target
    #   build_configuration: "Release",
    #   code_signing_identity: "iPhone Development" # optionally specify the codesigning identity
    # )

      # Build iOS App
    # build_number = ENV["build_number"]
    build_number = number_of_commits(all: true)
    #increment_build_number(build_number: number_of_commits)

    ipa_name  = "Provenance-#{git_branch}-#{build_number}.ipa"

    if is_ci?
      increment_build_number_in_plist(
        build_number: ci_build_number,
        target: 'Provenance'
      )
    end

    badge_alpha
    build_ios_adhoc(
      ipa_name: ipa_name,
      activeArchOnly: true,
      )

    # SCP to file server for storage
    # if is_ci?
    build_time = Time.now.strftime('%F')

    # begin
    #   upload_to_testflight
    # rescue => ex
    #   # don't fail the build
    #   UI.important("Testflight Something went wrong: #{ex}")
    # end

    dsym_name = File.basename(lane_context[SharedValues::DSYM_OUTPUT_PATH])

    # Push to Hockeyapp as Alpha release "2" alpha, "0" beta, "3" release
    begin
      UI.message "Upload to hockey-app with id #{$dev_domain}.provenance"
      publish_hockey(release_type: "2")
    rescue => ex
      # re-raise the exception unless it's something we're OK with ignoring
      # raise ex unless ex.message.include?('Error message of interest')
      # don't fail the build
      UI.important("Hockey App: Something went wrong: #{ex}")
    end

    # Upload to S3 bucket
    begin
      UI.message "Upload to S3 butcket IPA: #{ipa_name}, dSYM: #{dsym_name}"

      s3upload( ipa_name: ipa_name, dsym_name: dsym_name)
    rescue => ex
      # re-raise the exception unless it's something we're OK with ignoring
      # raise ex unless ex.message.include?('Error message of interest')
      # don't fail the build
      UI.important("S3: Something went wrong: #{ex}")
    end

    # SCP to web-server
    # begin
    #   UI.message "SCP'ing to #{build_time}"
    #   scp_upload(source: lane_context[SharedValues::IPA_OUTPUT_PATH], subfolder: build_time)
    #   scp_upload(source: lane_context[SharedValues::DSYM_OUTPUT_PATH], subfolder: build_time)
    # rescue => ex
    #     # re-raise the exception unless it's something we're OK with ignoring
    #     # raise ex unless ex.message.include?('Error message of interest')
    #   # don't fail the build
    #   UI.important("SCP Something went wrong: #{ex}")
    # end


    # uploadToWordpress(lane_context[SharedValues::IPA_OUTPUT_PATH])

    # Build tvOS app
    # match(app_identifier: ["#{$dev_domain}.provenance", "#{$dev_domain}.provenance.topshelf-extension"], type: "adhoc", platform: "tvos")
    # ipa_name = "ProvenanceTV-#{git_branch}-#{build_number}.ipa"
    # build_app(workspace: "Provenance.xcworkspace", scheme: "ProvenanceTV-Release", output_name: ipa_name, include_bitcode: false)


    # uploadToWordpress("./build/#{ipa_name}")
    # user = CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
    # keychain_entry = CredentialsManager::AccountManager.new(user: user)
    # password = keychain_entry.password

    reset_enviroment
  end

  private_lane :scp_upload do |options|

    source = options[:source]
    subfolder = options[:subfolder]

    unless File.exist?(source)
      UI.user_error!("Couldn't find file '#{source}'")
    end

    filename = File.basename(source)


    host = "provenance.joemattiello.com"
    port = "22"

    destination = "/usr/share/nginx/provenance.joemattiello.com/www/TravisBuilds/#{git_branch}/#{subfolder}/#{filename}"
    username = "provenance" #ENV["FASTLANE_USER"],

    UI.message "SCP'ing from #{source} to #{host}:#{destination}"

    scp(
      username: username,
      # password: ENV["FASTLANE_PASSWORD"],
      host: host,
      port: port,
      upload: {
        src: source,
        dst: destination
      }
    )
  end

  private_lane :badge_alpha do
    version_number = get_version_number(target: "Provenance")
    build_number = ENV["build_number"] || number_of_commits(all: true)

    if is_ci?
      build_number = ci_build_number || build_number
    end

    version = version_number.to_s

    add_badge(
      shield: "#{version}-#{build_number}-blue", 
      alpha: true, 
      dark: false,
      shield_no_resize: true)
  end

  private_lane :badge_beta do
    version_number = get_version_number(target: "Provenance")

    build_number = ENV["build_number"] || number_of_commits(all: true)

    if is_ci?
      build_number = ci_build_number || build_number
    end

    add_badge(
      shield: "#{version_number}-#{build_number}-blue", 
      alpha: false, 
      dark: false,
      shield_no_resize: true)
  end

  private_lane :reset_enviroment do
    plist_reset
    # codesign_toggle(automatic: true)
    # Make sure our directory is clean, except for changes Fastlane has made
    clean_build_artifacts
  end

  lane :check_env do
    desc "Environment Settings"
    puts "APP_IDENTIFIER: #{ENV['APP_IDENTIFIER']}"
    puts "APP_NAME: #{ENV['APP_NAME']}"
    puts "APP_SKU: #{ENV['APP_SKU']}"
    puts "LANG_CODE #{ENV['LANG_CODE']}"
  end

  desc "Setup Certs for Match - New Devs"
  lane :certificates do
    setup_certificates_private(type: "development")
    setup_certificates_private(type: "adhoc")
    # setup_certificates_private(type: "appstore")
    # update_devices
  end

  desc "Download cached Rome builds"
  lane :rome_download do
    swift_version = sh("swift --version | head -1 | sed 's/.*\((.*)\).*/\1/' | tr -d \"()\" | tr \" \" \"-\"")

    rome(
      command: "download",          # One of: download, upload, list
      platform: "iOS",              # Define which platform to build for (one of 'all', 'Mac', 'iOS', 'watchOS', 'tvOS', or comma-separated values of the formers except for 'all')
      cacheprefix: swift_version,
    )
  end

  private_lane :codesign_toggle do |options|
    load_keys

    automatic = options[:automatic]
    team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    disable_automatic_code_signing(path: "Provenance.xcodeproj",
      targets: ["Provenance"],
      code_sign_identity: "iPhone Distribution",
      profile_name: "match AdHoc #{$dev_domain}.provenance",
      bundle_identifier: "#{$dev_domain}.provenance",
      use_automatic_signing: automatic,
      team_id: team_id)

    disable_automatic_code_signing(path: "Provenance.xcodeproj",
      targets: ["Spotlight"],
      code_sign_identity: "iPhone Distribution",
      profile_name: "match AdHoc #{$dev_domain}.provenance.extension.spotlight",
      bundle_identifier: "#{$dev_domain}.provenance.extension.spotlight",
      use_automatic_signing: automatic,
      team_id: team_id)
  end

  private_lane :plist_set do |options|
    load_keys
    normal = options.fetch(:normal, true)
    suffix = normal ? "" : ".alpha"
    display_suffix = normal ? "" : " α" # or Beta β
    display_name = "$(TARGET_NAME)#{display_suffix}"

    # -- Update bundle names and ids
    # - iOS
    update_info_plist(
      plist_path: "Provenance/Provenance-Info.plist",
      display_name: display_name,
      app_identifier: "#{$dev_domain}.provenance#{suffix}"
    )

    # - Spotlight
    update_info_plist(
      plist_path: "Spotlight/Info.plist",
      display_name: display_name,
      app_identifier: "#{$dev_domain}.provenance#{suffix}.extension.spotlight"
    )

    # - tvOS
    # Use the same bundle ID as iOS so it's 'universal install'
    update_info_plist(
      plist_path: "ProvenanceTV/Info.plist",
      display_name: display_name,
      app_identifier: "#{$dev_domain}.provenance#{suffix}"
    )

    # - Top Shelf
    update_info_plist(
      plist_path: "TopShelf/Info.plist",
      display_name: display_name,
      app_identifier: "#{$dev_domain}.provenance#{suffix}.topshelf-extension"
    )
  end

  private_lane :setup_certificates_private do |options|
    load_keys

    # types "appstore", "development", "adhoc", "enterprise"
    type = options.fetch(:type, type)

    match(app_identifier: ["#{$dev_domain}.provenance", "#{$dev_domain}.provenance.extension.spotlight"], type: type, platform: "ios", readonly: true)
    match(app_identifier: ["#{$dev_domain}.provenance", "#{$dev_domain}.provenance.topshelf-extension"], type: type, platform: "tvos", readonly: true)
  end

  desc "Create Certs for Match"
  lane :create_certificates do
    load_keys

    create_certificates_private(type: "development")
    create_certificates_private(type: "adhoc")
    create_certificates_private(type: "appstore")
    #create_certificates_private(type: "enterprise")
  end

  private_lane :create_certificates_private do |options|
    load_keys

    # types "appstore", "development", "adhoc", "enterprise"
    type = options[:type]
    match(app_identifier: ["#{$dev_domain}.provenance", "#{$dev_domain}.provenance.extension.spotlight"], type: type, readonly: false, platform: "ios")
    match(app_identifier: ["#{$dev_domain}.provenance", "#{$dev_domain}.provenance.topshelf-extension"], type: type, readonly: false, platform: "tvos")
  end

  desc "Update device UDID list in iTunes connect from fastlane/devices.text"
  lane :update_devices do
    load_keys

    team_id = ENV["DEV_TEAM_ID"] # || CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    register_devices(devices_file: 'fastlane/devices.txt', team_id: team_id)
    match(type: "development", force_for_new_devices: true)
    match(type: "adhoc", force_for_new_devices: true)
  end

  desc "Clear your DerivedData"
  lane :derived_data do
    clear_derived_data
  end

  desc "Reset build enviroment"
  desc "Use this lane if you're having build issues"
  desc "Use `git stash` first to save any changes you may want to keep."
  lane :reset_checkout do

    UI.important "This lane is destructive and can delete unsaved changed."
    if !UI.confirm("Are you sure?")
      next
    end

    # clean xcode's build enviroment with xcodebuild
    UI.message "Cleaning target Provenance."
    xcclean(scheme: "Provenance")
    UI.message "Cleaning target Provenance TV."
    xcclean(scheme: "ProvenanceTV")

    if UI.confirm("Clear XCode's derived data?")
      clear_derived_data
    end

    UI.header("GIT Reset")
    clean = UI.confirm("Run 'git clean' to avoid removing untracked files? \nRecomended unless you have new files to save. Alternatively, use `git stash`.")
    disregard_gitignore = clean
    if clean
      disregard_gitignore = UI.confirm("Disregard .gitignore (Recomended)? If you want the equivalent of a fresh clone, and for all untracked and ignore files to also be removed.")
    end

    reset_git_repo(
      force: true,
      skip_clean: !clean,
      disregard_gitignore: disregard_gitignore
    )

    UI.success("Project directory reset.")
  end

  # Future Alpha builds
  private_lane :build_ios_adhoc do |options|
    activeArchOnly = options.fetch(:activeArchOnly, false)
    ipa_name = options.fetch(:ipa_name, 'Provenance.ipa')
    build_time = Time.now.strftime('%F')
    load_keys

    # Method used to export the archive.
    # Valid values are: app-store, ad-hoc, package, enterprise, development, developer-id
    export_method = options.fetch(:export_method, 'ad-hoc')
    build_configuration = options.fetch(:build_configuration, 'Release')
    scheme = options.fetch(:scheme, 'Provenance-Release')
    output_directory = "build/#{build_configuration}/#{build_time}"

    UI.message "Building #{scheme} as #{export_method} app #{ipa_name} to #{output_directory}.\nConfig: #{build_configuration}"

    build_app(
      workspace: "Provenance.xcworkspace",
      scheme: scheme,
      export_method: export_method,
      configuration: build_configuration,
      # codesigning_identity: "iPhone Developer",#{}"Joe Mattiello", "iPhone Distribution"
      silent: true,
      clean: false,
      skip_profile_detection: true,
      #skip_build_archive: true,
      output_directory: output_directory,
      output_name: ipa_name,
      include_bitcode: false,
      include_symbols: false,
      #xcargs: activeArchOnly ? "-arch arm64 ONLY_ACTIVE_ARCH=YES" : "",
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        method: export_method,
        iCloudContainerEnvironment: "Production",
        manifest: {
          appURL: "https://www.provenance-emu.com/builds/#{ipa_name}",
          displayImageURL: "https://provenance-emu.com/github-files/ipa-assets/Icon57x57.png", # 57x57
          fullSizeImageURL: "https://provenance-emu.com/github-files/ipa-assets/Icon512x512.png" # 512x512
        },
        provisioningProfiles: {
          "#{$dev_domain}.provenance" => "match AdHoc #{$dev_domain}.provenance", # match AdHoc match AppStore match Development
          "#{$dev_domain}.provenance.extension.spotlight" => "match AdHoc #{$dev_domain}.provenance.extension.spotlight"
        },
        compileBitcode: false,
        uploadBitcode: false,
      }
    )
  end

  desc "Exports a new Developer Build"
  lane :build_developer do |options|
    scheme = options.fetch(:scheme, 'Provenance-Release')
    load_keys

    build_app(
      workspace: "Provenance.xcworkspace",
      scheme: scheme,
      export_method: "development", # Method used to export the archive. Valid values are: app-store, ad-hoc, package, enterprise, development, developer-id
      configuration: "Release",
      # codesigning_identity: "iPhone Developer",#{}"Joe Mattiello", "iPhone Distribution"
      clean: false,
      silent: true,
      output_directory: "Builds",
      #output_name: ipa_name,
      include_bitcode: false,
      include_symbols: true,
      #xcargs: activeArchOnly ? "-arch arm64 ONLY_ACTIVE_ARCH=YES" : "",
      export_options: {
        method: "development",
        compileBitcode: false,
        uploadBitcode: false,
      }
    )

  end

  desc "Exports a new AppStore Build"
  lane :build_appstore do
    load_keys

    build_app(
      workspace: "Provenance.xcworkspace",
      scheme: "Provenance-Release",
      export_method: "app-store", # Method used to export the archive. Valid values are: app-store, ad-hoc, package, enterprise, development, developer-id
      configuration: "Release",
      # codesigning_identity: "iPhone Developer",#{}"Joe Mattiello", "iPhone Distribution"
      clean: false,
      silent: true,
      #output_directory: output_directory,
      #output_name: ipa_name,
      include_bitcode: false,
      include_symbols: false,
      #xcargs: activeArchOnly ? "-arch arm64 ONLY_ACTIVE_ARCH=YES" : "",
      export_options: {
        method: "app-store",
        # manifest: {
        #   appURL: "https://www.provenance-emu.com/builds/#{ipa_name}",
          # displayImageURL: "https://provenance-emu.com/github-files/ipa-assets/Icon57x57.png", # 57x57
          # fullSizeImageURL: "https://provenance-emu.com/github-files/ipa-assets/Icon512x512.png" # 512x512
        # },
        provisioningProfiles: {
          "#{$dev_domain}.provenance" => "match AppStore #{$dev_domain}.provenance", # match AdHoc match AppStore match Development
          "#{$dev_domain}.provenance.extension.spotlight" => "match AppStore #{$dev_domain}.provenance.extension.spotlight"
        },
        compileBitcode: false,
        uploadBitcode: false,
      }
    )

  end

  private_lane :submit_appstore do
    load_keys
    pilot(app_identifier: "#{$dev_domain}.provenance")
  end

  # private_lane :versionIcon do
  #   # see https://github.com/revolter/fastlane-plugin-icon_versioning
  #   # https://github.com/HazAT/fastlane-plugin-badge
  # https://github.com/HazAT/badge
  # end

  # See https://www.raywenderlich.com/136168/fastlane-tutorial-getting-started-2
  # https://docs.fastlane.tools/getting-started/ios/screenshots/
  # desc "Take screenshots"
  # lane :screenshot do
  #   snapshot
  # end

  desc "Lane to run bootstrap carthage in new checkout for iOS only"
  lane :carthage_bootstrap_ios do |options|
    carthage_bootstrap(
      platform: "iOS"
    )
  end

  desc "Lane to run bootstrap carthage in new checkout for tvOS only"
  lane :carthage_bootstrap_tvos do |options|
    carthage_bootstrap(
      platform: "tvOS"
    )
  end

  desc "Lane to run bootstrap carthage in new checkout"
  desc "Option: `platform` tvOS,iOS"
  lane :carthage_bootstrap do |options|
    platform = options.fetch(:platform, 'tvOS,iOS')

    carthage_private(
      command: "bootstrap",
      platform: platform
    )
  end

  desc "Lane to run build all carthage dependencies"
  desc "Option: `platform` tvOS,iOS"
  lane :carthage_build do |options|
    platform = options.fetch(:platform, 'tvOS,iOS')

    carthage_private(
      command: "build",
      platform: platform
    )
  end

  desc "Lane to update all carthage dependencies to latest versions"
  desc "Option: `platform` tvOS,iOS"
  lane :carthage_update do |options|
    platform = options.fetch(:platform, 'tvOS,iOS')

    carthage_private(
      command: "update",
      platform: platform
    )
  end

  desc "Lane to update all carthage dependencies to latest versions for iOS only"
  lane :carthage_update_ios do |options|
    carthage_update(
      platform: "iOS"
    )
  end

  desc "Lane to update all carthage dependencies to latest versions for tvOS only"
  lane :carthage_update_tvos do |options|
    carthage_update(
      platform: "tvOS"
    )
  end

  private_lane :carthage_private do |options|
    command = options.fetch(:command, 'bootstrap')
    platform = options.fetch(:platform, 'tvOS,iOS')
    project_directory = options.fetch(:project_directory, './')

    UI.message "Running Carthage command '#{command}' for platform(s) '#{platform}' in directory '#{project_directory}'"

    carthage(
      command: command,
      platform: platform,
      use_binaries: true,
      cache_builds: true,
      use_ssh: true,
      project_directory: project_directory
    )
  end

# See https://docs.fastlane.tools/actions/resign/
#   lane :resign do
#     resign(
#   ipa: "path/to/ipa", # can omit if using the `ipa` action
#   signing_identity: "iPhone Distribution: Luka Mirosevic (0123456789)",
#   provisioning_profile: {
#     "com.example.awesome-app" => "path/to/profile",
#     "com.example.awesome-app.app-extension" => "path/to/app-extension/profile"
#   }
# )
#   end

# TODO: iCloud
private_lane :set_icloud_container do
  update_icloud_container_identifiers(
    entitlements_file: "/path/to/entitlements_file.entitlements",
    icloud_container_identifiers: ["iCloud.com.companyname.appname"]
  )
end

# Resign and copy to device
private_lane :resign_and_copy do
  # TODO: this
end

# Copy to device
private_lane :copy_to_device do
  # Need to first install ios-deploy
  # npm -g i ios-deploy
  # can call ios-deply --detect to list devices
  install_on_device(
    skip_wifi: true, # Don't look for devices on wifi
    # device_id: "a3be6c9ff7e5c3c6028597513243b0f933b876d4", # First device if no ID given
    ipa: "./app.ipa"
  )
end

# Publish to hockeyapp
private_lane :publish_hockey do |options|
  # Send to hockey app
  # NOTE: hockey action will use the latest ipa and latest dsym built
  ENV["HOCKEY_APP_TOKEN"] = "6f0fc66f062044349a25aaeede834921"
  ENV["HOCKEY_BETA_APP_ID"] = "a1fd56cd852d4c959988484eba69f724"

  hockey(
    api_token: ENV['HOCKEY_APP_TOKEN'],
    notes: "The Official Provenance Beta",
    public_identifier: ENV['HOCKEY_BETA_APP_ID'],
    release_type: options[:release_type],
    notify: "0")

    # Alert discord?
    hockLink = lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK]
    UI.message "Hockeyapp download link is at #{hockLink}."
end

  # error block is executed when a error occurs
  # error do |lane, exception|
  #   slack(
  #     # message with short human friendly message
  #     message: exception.to_s,
  #     success: false,
  #     # Output containing extended log output
  #     payload: { "Output" => exception.error_info.to_s }
  #   )
  # end
end
