# A list of devices you want to take the screenshots from
devices([
  "iPhone X",
  "AppleTV",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
  "iPad Retina",
  "iPad Pro"
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
# scheme "SchemeName"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace "./Provenace.xcworkspace"

# For more information about all available options run
# fastlane action snapshot
