mednafen_SOURCES	+= 	snes_faust/cpu.cpp snes_faust/snes.cpp snes_faust/apu.cpp snes_faust/cart.cpp snes_faust/input.cpp snes_faust/ppu.cpp snes_faust/ppu_st.cpp snes_faust/ppu_mt.cpp
mednafen_SOURCES	+=	snes_faust/cart/dsp1.cpp snes_faust/cart/dsp2.cpp snes_faust/cart/sdd1.cpp snes_faust/cart/cx4.cpp snes_faust/cart/superfx.cpp
mednafen_SOURCES	+=	snes_faust/cart/sa1.cpp snes_faust/cart/sa1cpu.cpp
mednafen_SOURCES	+=	snes_faust/msu1.cpp
mednafen_SOURCES	+=	snes_faust/debug.cpp snes_faust/dis65816.cpp
#
mednafen_SOURCES	+=	snes_faust/ppu_mtrender.cpp
