//
//  MednafenGameCoreOptions+MultiTap_SNES.swift
//  PVMednafen
//
//  Created by Joseph Mattiello on 3/17/26.
//  Copyright © 2026 Provenance EMU. All rights reserved.
//
//  CRC32 list sourced from snes9x (PVSNESEmulatorCore.mm) — these are
//  CRC32 hashes of the headerless ROM data for games that support the
//  SNES Multitap (port 2 multitap, 5 players).

import Foundation

@objc public extension MednafenGameCoreOptions {
    /// CRC32 hashes (lowercase 8-char hex) of SNES games that use the
    /// multitap adapter (controller in port 1, multitap in port 2 — 5 players).
    @objc static var multiTapSNESGames: [String] {
        struct Static {
            static let list: [String] = [
                "5613f172", // Bakukyuu Renpatsu!! Super B-Daman (Japan)
                "94bfcc92", // Bakutou Dochers - Bumps-jima wa Oosawagi (Japan)
                "29fbd13d", // Barkley Shut Up and Jam! (Europe)
                "8aff96d0", // Barkley no Power Dunk (Japan)
                "726b6c5a", // Barkley Shut Up and Jam! (USA)
                "5f5e9b0b", // Battle Cross (Japan)
                "d79c1ec5", // Battle Jockey (Japan)
                "25391c9f", // Bill Walsh College Football (USA)
                "9fea854d", // Bomber Man B-Daman (Japan)
                "bbcd16f4", // Soccer Shootout (Europe)
                "d96b3936", // J.League Excite Stage '94 (Japan)
                "c9e33615", // J.League Excite Stage '94 (Japan) (Rev 1)
                "ee314ae5", // Capcom's Soccer Shootout (USA)
                "89178bc0", // Capcom's Soccer Shootout (USA) (Beta)
                "846151c8", // Chibi Maruko-chan - Harikiri 365-nichi no Maki (Japan)
                "f4defcae", // Chibi Maruko-chan - Mezase! Minami no Island!! (Japan)
                "ce842c6d", // College Slam (USA)
                "79663a93", // Crystal Beans from Dungeon Explorer (Japan)
                "dbf4a8ab", // Dino Dini's Soccer! (Europe) (En,Fr,De)
                "038212ea", // Dragon - The Bruce Lee Story (Europe)
                "407c5c24", // Dragon - The Bruce Lee Story (USA)
                "cc24110a", // Dream Basketball - Dunk & Hoop (Japan)
                "ebcc121c", // Dynamic Stadium (Japan)
                "62abaee1", // Elite Soccer (USA)
                "6d16f5e7", // World Cup Striker (Europe) (En,Fr,De)
                "6928d52a", // World Cup Striker (Europe) (En,Fr,De) (Beta)
                "cab690a1", // World Cup Striker (Japan)
                "75058ede", // ESPN National Hockey Night (USA)
                "28c2d764", // FIFA - A Caminho Da Copa 98 (Brazil)
                "5e4f4856", // FIFA - Road to World Cup 98 (Europe)
                "a350821a", // FIFA International Soccer (Europe)
                "4fa1d452", // FIFA International Soccer (Japan)
                "56296426", // FIFA International Soccer (USA)
                "8faf17e5", // FIFA Soccer 96 (Europe)
                "7566347d", // FIFA Soccer 96 (USA)
                "470eabe5", // FIFA 97 (Europe)
                "38916376", // FIFA Soccer 97 (USA)
                "e06fae58", // Finalset (Japan)
                "e500c7ba", // FireStriker (USA)
                "bbbbabb6", // FireStriker (USA) (Beta)
                "46acfc84", // Holy Striker (Japan)
                "9b1ea779", // Fever Pitch Soccer (Europe)
                "25c8f98a", // Fever Pitch Soccer (Europe) (Beta)
                "60dc3634", // Head-On Soccer (USA)
                "d05114c0", // From TV Animation Slam Dunk - SD Heat Up!! (Japan)
                "184b07dc", // Go! Go! Dodge League (Japan)
                "06e6e66d", // Go! Go! Dodge League (Japan) (Rev 1)
                "3d2352ea", // Hammer Lock Wrestling (USA)
                "d5fb8c83", // Tenryuu Genichirou no Pro Wres Revolution (Japan)
                "19e67dff", // Hat Trick Hero 2 (Japan)
                "0b94ccd4", // Hebereke no Oishii Puzzle wa Irimasenka (Japan)
                "9f6d0228", // Human Grand Prix III - F1 Triple Battle (Japan)
                "47453477", // Human Grand Prix IV - F1 Dream Battle (Japan)
                "5c4b2544", // Hungry Dinosaurs (Europe)
                "7abdb576", // Harapeko Bakka (Japan)
                "cba724ba", // International Superstar Soccer Deluxe (Europe)
                "0a20e602", // International Superstar Soccer Deluxe (USA)
                "e7559d73", // Jikkyou World Soccer 2 - Fighting Eleven (Japan)
                "261e0ea1", // Jikkyou World Soccer 2 - Fighting Eleven (Japan) (Beta)
                "dd871511", // J.League Excite Stage '95 (Japan)
                "c286ee0c", // J.League Excite Stage '95 (Japan) (Sample)
                "e044e0f1", // J.League Excite Stage '96 (Japan)
                "857bbfab", // J.League Excite Stage '96 (Japan) (Rev 1)
                "b81828ec", // J.League Soccer Prime Goal (Japan)
                "7538f598", // J.League Soccer Prime Goal (Japan) (Rev 1)
                "26664bb4", // J.League Super Soccer '95 - Jikkyou Stadium (Japan)
                "247c17d3", // J.R.R. Tolkien's The Lord of the Rings Vol. 1 (Europe)
                "8b172b4e", // J.R.R. Tolkien's The Lord of the Rings Vol. 1 (Germany)
                "cd2150c8", // J.R.R. Tolkien's The Lord of the Rings Vol. 1 (USA)
                "94c1d85c", // Jikkyou Power Pro Wrestling '96 - Max Voltage (Japan)
                "bba55bec", // Jimmy Connors Pro Tennis Tour (Europe)
                "bea289fc", // Jimmy Connors Pro Tennis Tour (France)
                "e2294a8e", // Jimmy Connors Pro Tennis Tour (Germany)
                "a95bef02", // Jimmy Connors Pro Tennis Tour (Japan)
                "913f1555", // Jimmy Connors Pro Tennis Tour (USA)
                "69642b00", // JWP Joshi Pro Wres - Pure Wrestle Queens (Japan)
                "c819109c", // Kingyo Chuuihou! - Tobidase! Game Gakuen (Japan)
                "7bf62174", // Kunio-kun no Dodge Ball Da yo Zenin Shuugou! (Japan)
                "fdf2f478", // Looney Tunes Basketball (Europe)
                "6d3bc96f", // Looney Tunes B-Ball (USA)
                "a7d31544", // Madden NFL '94 (Europe)
                "1e4b3858", // NFL Pro Football '94 (Japan)
                "8bed5914", // Madden NFL '94 (USA)
                "4b0c7993", // Madden NFL 95 (Europe)
                "021a3f69", // Madden NFL 95 (USA)
                "51a1fe86", // Madden NFL 96 (USA)
                "4c78d04a", // Madden NFL 96 (USA) (Sample)
                "abcf026e", // Madden NFL 97 (USA)
                "cf10cc01", // Madden NFL 98 (USA)
                "b4f64a09", // Micro Machines (Europe)
                "364e68bb", // Micro Machines (USA)
                "1619b619", // Micro Machines 2 - Turbo Tournament (Europe)
                "70740cf4", // Mizuki Shigeru no Youkai Hyakkiyakou (Japan)
                "60844b65", // Multi Play Volleyball (Japan)
                "d4dc20e1", // Natsume Championship Wrestling (USA)
                "e52b9af6", // NBA Give 'n Go (Europe)
                "7ecaa194", // NBA Jikkyou Basket - Winning Dunk (Japan)
                "68c8b643", // NBA Give 'n Go (USA)
                "f1fe37a4", // NBA Hang Time (Europe)
                "262ce76b", // NBA Hang Time (USA)
                "2b8e81c6", // NBA Jam (Europe)
                "fa9a577a", // NBA Jam (Europe) (Rev 1)
                "118b162e", // NBA Jam (Japan)
                "43f1c013", // NBA Jam (USA)
                "8f42cae7", // NBA Jam (USA) (Rev 1)
                "0318705b", // NBA Jam (USA) (Beta)
                "d48c8041", // NBA Jam - Tournament Edition (Europe)
                "3c169224", // NBA Jam - Tournament Edition (Japan)
                "1fbc1ddb", // NBA Jam - Tournament Edition (USA)
                "8d7b1828", // NBA Jam - Tournament Edition (USA) (Beta)
                "56fdbb8c", // NBA Live 95 (Europe)
                "500f57d3", // NBA Live 95 (Japan)
                "1cd2393d", // NBA Live 95 (USA)
                "17689c62", // NBA Live 96 (Europe)
                "042a6495", // NBA Live 96 (USA)
                "2c680c99", // NBA Live 97 (Europe)
                "5115b8e5", // NBA Live 97 (USA)
                "514bfcb5", // NBA Live 98 (USA)
                "b07cfa91", // NCAA Final Four Basketball (USA)
                "2641c12a", // NCAA Football (USA)
                "87bc35af", // NFL Quarterback Club (Europe)
                "1c036b4f", // NFL Quarterback Club '95 (Japan)
                "79f16421", // NFL Quarterback Club (USA)
                "78d10e07", // NFL Quarterback Club (USA) (Beta)
                "9708abe3", // NFL Quarterback Club 96 (Europe)
                "3a4c0de6", // NFL Quarterback Club 96 (Japan)
                "e557689f", // NFL Quarterback Club 96 (USA)
                "b87abc7e", // NFL Quarterback Club 96 (USA) (Beta)
                "208fbf59", // NHL Hockey '94 (Europe)
                "bc37d603", // NHL Pro Hockey '94 (Japan)
                "42212a77", // NHL '94 (USA)
                "00ff0c74", // NHL '94 (USA) (Beta)
                "6930b67a", // NHL 95 (Europe)
                "2e9b1463", // NHL 95 (USA)
                "148b2734", // NHL 96 (Europe)
                "b6c6e7f3", // NHL 96 (USA)
                "313b9622", // NHL 97 (Europe)
                "1a53b7a8", // NHL 97 (Europe) (Rev 1)
                "06badb74", // NHL 97 (USA)
                "4f72aa8c", // NHL 97 (USA) (Rev 1)
                "03cad2d2", // NHL 98 (USA)
                "3ed21333", // Olympic Summer Games (Europe)
                "6b882d11", // Olympic Summer Games (USA)
                "0a2e4c2f", // Rushing Beat Shura (Japan)
                "8071e5db", // Peace Keepers, The (USA)
                "78f229dc", // Jigsaw Party (Japan)
                "bb6c3c54", // Pieces (USA)
                "689a7a79", // Puzzle'n Desu! (Japan)
                "adf4ffce", // Rap Jam - Volume One (USA)
                "a3876f76", // Saturday Night Slam Masters (Europe)
                "a6e028c2", // Muscle Bomber - The Body Explosion (Japan)
                "54161830", // Saturday Night Slam Masters (USA)
                "c5cb2f26", // Secret of Mana (Europe)
                "de112322", // Secret of Mana (Europe) (Rev 1)
                "6be4ca95", // Secret of Mana (France)
                "e9334b9e", // Secret of Mana (France) (Rev 1)
                "b069bb3a", // Secret of Mana (Germany)
                "b8049e3c", // Seiken Densetsu 2 (Japan)
                "d0176b24", // Secret of Mana (USA)
                "e6b9a402", // Shijou Saikyou no Quiz Ou Ketteisen Super (Japan)
                "58da330c", // Shin Nihon Pro Wrestling - Chou Senshi (Japan)
                "6cbbd019", // Shin Nihon Pro Wrestling Kounin '94 (Japan)
                "a467c220", // Shin Nihon Pro Wrestling Kounin '95 (Japan)
                "6f7d1745", // Smash Tennis (Europe)
                "3ccba79c", // Smash Tennis (Europe) (Beta)
                "2bcbff26", // Super Family Tennis (Japan)
                "315af696", // Sporting News Baseball, The (USA)
                "70d9c906", // Sterling Sharpe - End 2 End (USA)
                "97357a1b", // Street Sports - Street Hockey '95 (USA)
                "29296976", // Street Hockey '95 (USA) (Beta)
                "e013d5b0", // Street Racer (Europe)
                "2ae69849", // Street Racer (Europe) (Rev 1)
                "d1c1f675", // Street Racer (Japan)
                "63e8b7d5", // Street Racer (USA)
                "1934f184", // Street Racer (USA) (Beta)
                "72123ef0", // Sugoi Hebereke (Japan)
                "366c84f3", // Sugoro Quest++ - Dicenics (Japan)
                "678501f2", // Super Bomberman (Europe)
                "7989891a", // Super Bomber Man (Japan)
                "63a8e2c6", // Super Bomberman (USA)
                "fc633ecb", // Super Bomber Man - Panic Bomber W (Japan)
                "c60a4191", // Super Bomberman 2 (Europe)
                "fb259f4f", // Super Bomber Man 2 (Japan)
                "2aa1ddf8", // Super Bomber Man 2 (Japan) (Caravan You Taikenban)
                "9c1f11e4", // Super Bomberman 2 (USA)
                "a096a6e5", // Super Bomberman 3 (Europe)
                "9ecb0fe6", // Super Bomber Man 3 (Japan)
                "002fa245", // Super Bomber Man 3 (Japan) (Beta)
                "3bbaeb19", // Super Bomber Man 4 (Japan)
                "06b1f0f5", // Super Bomber Man 5 (Japan)
                "4590ae9d", // Super Bomber Man 5 (Japan) (Caravan Event Ban)
                "4f0b96fa", // Super Final Match Tennis (Japan)
                "8fac5efd", // Super Fire Pro Wrestling 2 (Japan)
                "b48513fe", // Super Fire Pro Wrestling 2 (Japan) (Beta)
                "93f778af", // Super Fire Pro Wrestling III - Easy Type (Japan)
                "4dfb9072", // Super Fire Pro Wrestling III - Final Bout (Japan)
                "978dc1ca", // Super Fire Pro Wrestling III - Final Bout (Japan) (Rev 1)
                "3227f1b1", // Super Fire Pro Wrestling - Queen's Special (Japan)
                "e279ebe3", // Super Fire Pro Wrestling Special (Japan)
                "1a13435c", // Super Fire Pro Wrestling Special (Japan) (Rev 1)
                "959db484", // Super Fire Pro Wrestling X (Japan)
                "82de1380", // Super Fire Pro Wrestling X Premium (Japan)
                "74c75074", // Super Formation Soccer II (Japan)
                "d547c5d2", // Super Formation Soccer 94 - World Cup Edition (Japan)
                "bf1f2e16", // Super Formation Soccer 94 - World Cup Final Data (Japan)
                "798352bf", // Super Formation Soccer 95 della Serie A (Japan)
                "1cf83bc2", // Super Formation Soccer 95 della Serie A (Japan) (UCC Xaqua)
                "f42272cb", // Super Formation Soccer 96 - World Club Edition (Japan)
                "fb1d16c4", // Super Ice Hockey (Europe)
                "a3890d4f", // Super Hockey '94 (Japan)
                "60305047", // Super Kyousouba - Kaze no Sylphid (Japan)
                "56f3a65a", // Super Power League (Japan)
                "271e1f3f", // Super Puyo Puyo Tsuu (Japan)
                "3276e449", // Magic Johnson no Super Slam Dunk (Japan)
                "3effc9e5", // Super Slam Dunk (USA)
                "5be4a7e3", // Super Tekkyuu Fight! (Japan)
                "329024c7", // Super Tetris 3 (Japan)
                "fd851819", // Syndicate (Europe)
                "181cae99", // Syndicate (Europe) (Beta)
                "63c52dc4", // Syndicate (Japan)
                "d74570d3", // Syndicate (USA)
                "383face4", // Takeda Nobuhiro no Super League Soccer (Japan)
                "ae78b20e", // Tiny Toon Adventures - Wild & Wacky Sports (Europe)
                "0f3b758d", // Tiny Toon Adventures - Wild & Wacky Sports (Europe) (Rev 1)
                "f13002c7", // Tiny Toon Adventures - Wild & Wacky Sports (Europe) (Beta)
                "01344c8e", // Tiny Toon Adventures - Dotabata Daiundoukai (Japan)
                "afe72ff0", // Tiny Toon Adventures - Wacky Sports Challenge (USA)
                "493fdb13", // Top Gear 3000 (Europe)
                "b9b9df06", // Planet's Champ TG 3000, The (Japan)
                "a20be998", // Top Gear 3000 (USA)
                "26a9c3f4", // Turbo Toons (Europe)
                "ecb8a53a", // Virtual Soccer (Europe)
                "1d20cac2", // J.League Super Soccer (Japan)
                "accb5950", // Vegas Stakes (Europe)
                "a6bb5a7a", // Las Vegas Dream in Golden Paradise (Japan)
                "03a0e935", // Vegas Stakes (USA)
                "6383d9a5", // Virtual Soccer (USA) (Proto)
                "a9fcfd53", // Vs. Collection (Japan)
                "5fc89932", // Wedding Peach (Japan)
                "8b477300", // WCW Super Brawl Wrestling (USA)
                "a5a3bfbc", // WWF Raw (Europe)
                "3e0038bf", // WWF Raw (USA)
                "02855382", // Yuujin no Furi Furi Girls (Japan)
                "48e9887f", // Zero 4 Champ RR (Japan)
                "3c6a8dc8", // Zero 4 Champ RR-Z (Japan)
            ]
        }
        return Static.list
    }

    /// CRC32 of the 8-player homebrew N-Warp Daisakusen (sport1 + sport2 multitap).
    @objc static var multiTapSNES8PlayerGames: [String] {
        return ["be08d788"] // N-Warp Daisakusen v1.1 (Homebrew)
    }
}
