objc: true
clean: true
sdk: iphonesimulator

theme: ../Themes/apple

module: HockeySDK
module_version: 5.1.2
author: Microsoft Corp
author_url: https://www.microsoft.com

readme: ../../README.md
documentation: ../Guides/*.md
custom_categories:
  - name: Guides
    children:
    - Installation & Setup
    - Migration Kits
  - name: How To
    children:
    - App Versioning
    - Set Custom AlertViewHandler
    - Upload Symbols
  - name: Troubleshooting
    children:
    - Crash Reporting Not Working
  - name: Release Notes
    children:
    - Changelog

umbrella_header: ../../Classes/HockeySDK.h

root_url: https://support.hockeyapp.net/kb/api
github_url: https://github.com/bitstadium/HockeySDK-iOS/
github_file_prefix: "https://github.com/bitstadium/HockeySDK-iOS/"

skip_undocumented: true

output: Generated/
