
// Do not edit!  This file was autogenerated
//      by ./Provenance/Resources/createVersionHeader.sh
//      on Tue Jul 24 05:30:29 EDT 2018
//      user jmattiello
//      for build target Provenance
//
// gitrevision and gitdate are as reported by git at that point in time,
// compiledate and compiletime are being filled gcc at compilation

#include <stdlib.h>

static NSString* const kAppVersion              = @"1.5";
static NSString* const kGITRevisionNumber       = @"2010";
static NSString* const kGITTag                  = @"1.4-1193-gfff4a126-dirty";
static NSString* const kGITDate                 = @"Mon Jul 23 23:16:14 2018";
static NSString* const kGITBranch               = @"develop";
static NSString* const kAppBuildConfiguration   = @"Debug";

// Suppress warnings incase you choose not to use these variables
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused"

static const char* gitrevision          = "2010";
static const char* gittag               = "1.4-1193-gfff4a126-dirty";
static const char* gitdate              = "Mon Jul 23 23:16:14 2018";
static const char* gitbranch            = "develop";
static const char* appversion           = "1.5";
static const char* buildconfiguration   = "Debug";
// static const char* compiletime          = __TIME__;
// static const char* compiledate          = __DATE__;

#pragma GCC diagnostic pop

// Diagnostic info
/*
    Info.plist path:/Users/jmattiello/Workspace/Provenance/Provenance-jmattiello/Provenance/Provenance-Info.plist
    PWD : /Users/jmattiello/Workspace/Provenance/Provenance-jmattiello
    XCode version 9F2000
    PATH : /opt/wine-staging/bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/python:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jmattiello/.rvm/bin
*/
