// Do not edit!  This file was autogenerated
//      by ./Provenance/Resources/createVersionHeader.sh
//      on Jeu  9 aoû 2018 02:23:47 CEST
//      user wwwb23prodtminfo
//      for build target Provenance
//
// gitrevision and gitdate are as reported by git at that point in time,
// compiledate and compiletime are being filled gcc at compilation

public let kAppVersion : String = "1.5"
public let kGITRevisionNumber : String = "2089"
public let kGITTag : String = "1.4-1272-gf81d4bb0-dirty"
public let kGITDate : String = "Thu Aug 9 01:20:41 2018"
public let kGITBranch : String = "feature/Core-Beetle-Saturn"
public let kAppBuildConfiguration : String  = "Release"

public let gitrevision          = "2089"
public let gittag               = "1.4-1272-gf81d4bb0-dirty"
public let gitdate              = "Thu Aug 9 01:20:41 2018"
public let gitbranch            = "feature/Core-Beetle-Saturn"
public let appversion           = "1.5"
public let buildconfiguration   = "Release"
// public let compiletime          = __TIME__
// public let compiledate          = __DATE__

// Diagnostic info
/*
    Info.plist path:/Users/wwwb23prodtminfo/NetBeansProjects/Provenance/Provenance/Info.plist
    PWD : /Users/wwwb23prodtminfo/NetBeansProjects/Provenance
    XCode version 9F2000
    PATH : /opt/local/bin:/opt/local/sbin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Tools:/usr/local/opt/mysql@5.6/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
*/
