// Do not edit!  This file was autogenerated
//      by ./Provenance/Resources/createVersionHeader.sh
//      on Tue Jul 24 05:30:29 EDT 2018
//      user jmattiello
//      for build target Provenance
//
// gitrevision and gitdate are as reported by git at that point in time,
// compiledate and compiletime are being filled gcc at compilation

public let kAppVersion : String = "1.5"
public let kGITRevisionNumber : String = "2010"
public let kGITTag : String = "1.4-1193-gfff4a126-dirty"
public let kGITDate : String = "Mon Jul 23 23:16:14 2018"
public let kGITBranch : String = "develop"
public let kAppBuildConfiguration : String  = "Debug"

public let gitrevision          = "2010"
public let gittag               = "1.4-1193-gfff4a126-dirty"
public let gitdate              = "Mon Jul 23 23:16:14 2018"
public let gitbranch            = "develop"
public let appversion           = "1.5"
public let buildconfiguration   = "Debug"
// public let compiletime          = __TIME__
// public let compiledate          = __DATE__

// Diagnostic info
/*
    Info.plist path:/Users/jmattiello/Workspace/Provenance/Provenance-jmattiello/Provenance/Provenance-Info.plist
    PWD : /Users/jmattiello/Workspace/Provenance/Provenance-jmattiello
    XCode version 9F2000
    PATH : /opt/wine-staging/bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/python:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jmattiello/.rvm/bin
*/
