# CMake generated Testfile for 
# Source directory: /Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core
# Build directory: /Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Source/UnitTests/Core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(MMIOTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/MMIOTest.app/MMIOTest")
  set_tests_properties(MMIOTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;1;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(MMIOTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/MMIOTest.app/MMIOTest")
  set_tests_properties(MMIOTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;1;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(MMIOTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/MMIOTest.app/MMIOTest")
  set_tests_properties(MMIOTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;1;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(MMIOTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/MMIOTest.app/MMIOTest")
  set_tests_properties(MMIOTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;1;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
else()
  add_test(MMIOTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(PageFaultTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/PageFaultTest.app/PageFaultTest")
  set_tests_properties(PageFaultTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;2;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(PageFaultTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/PageFaultTest.app/PageFaultTest")
  set_tests_properties(PageFaultTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;2;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(PageFaultTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/PageFaultTest.app/PageFaultTest")
  set_tests_properties(PageFaultTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;2;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(PageFaultTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/PageFaultTest.app/PageFaultTest")
  set_tests_properties(PageFaultTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;2;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
else()
  add_test(PageFaultTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CoreTimingTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/CoreTimingTest.app/CoreTimingTest")
  set_tests_properties(CoreTimingTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;3;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CoreTimingTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/CoreTimingTest.app/CoreTimingTest")
  set_tests_properties(CoreTimingTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;3;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CoreTimingTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/CoreTimingTest.app/CoreTimingTest")
  set_tests_properties(CoreTimingTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;3;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CoreTimingTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/CoreTimingTest.app/CoreTimingTest")
  set_tests_properties(CoreTimingTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;3;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
else()
  add_test(CoreTimingTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DSPAcceleratorTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/DSPAcceleratorTest.app/DSPAcceleratorTest")
  set_tests_properties(DSPAcceleratorTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;5;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DSPAcceleratorTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/DSPAcceleratorTest.app/DSPAcceleratorTest")
  set_tests_properties(DSPAcceleratorTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;5;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DSPAcceleratorTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/DSPAcceleratorTest.app/DSPAcceleratorTest")
  set_tests_properties(DSPAcceleratorTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;5;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DSPAcceleratorTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/DSPAcceleratorTest.app/DSPAcceleratorTest")
  set_tests_properties(DSPAcceleratorTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;5;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
else()
  add_test(DSPAcceleratorTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DSPAssemblyTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/DSPAssemblyTest.app/DSPAssemblyTest")
  set_tests_properties(DSPAssemblyTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;6;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DSPAssemblyTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/DSPAssemblyTest.app/DSPAssemblyTest")
  set_tests_properties(DSPAssemblyTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;6;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DSPAssemblyTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/DSPAssemblyTest.app/DSPAssemblyTest")
  set_tests_properties(DSPAssemblyTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;6;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DSPAssemblyTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/DSPAssemblyTest.app/DSPAssemblyTest")
  set_tests_properties(DSPAssemblyTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;6;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
else()
  add_test(DSPAssemblyTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ESFormatsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/ESFormatsTest.app/ESFormatsTest")
  set_tests_properties(ESFormatsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;13;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ESFormatsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/ESFormatsTest.app/ESFormatsTest")
  set_tests_properties(ESFormatsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;13;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ESFormatsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/ESFormatsTest.app/ESFormatsTest")
  set_tests_properties(ESFormatsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;13;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ESFormatsTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/ESFormatsTest.app/ESFormatsTest")
  set_tests_properties(ESFormatsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;13;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
else()
  add_test(ESFormatsTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(FileSystemTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/FileSystemTest.app/FileSystemTest")
  set_tests_properties(FileSystemTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;15;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(FileSystemTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/FileSystemTest.app/FileSystemTest")
  set_tests_properties(FileSystemTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;15;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(FileSystemTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/FileSystemTest.app/FileSystemTest")
  set_tests_properties(FileSystemTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;15;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(FileSystemTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/FileSystemTest.app/FileSystemTest")
  set_tests_properties(FileSystemTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;15;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
else()
  add_test(FileSystemTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(PowerPCTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Debug/PowerPCTest.app/PowerPCTest")
  set_tests_properties(PowerPCTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;24;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(PowerPCTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/Release/PowerPCTest.app/PowerPCTest")
  set_tests_properties(PowerPCTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;24;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(PowerPCTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/MinSizeRel/PowerPCTest.app/PowerPCTest")
  set_tests_properties(PowerPCTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;24;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(PowerPCTest "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/cmake/Binaries/Tests/RelWithDebInfo/PowerPCTest.app/PowerPCTest")
  set_tests_properties(PowerPCTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/CMakeLists.txt;21;add_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;24;add_dolphin_test;/Users/jmattiello/Workspace/Provenance/Provenance/Cores/Dolphin/dolphin-ios/Source/UnitTests/Core/CMakeLists.txt;0;")
else()
  add_test(PowerPCTest NOT_AVAILABLE)
endif()
