exiftool.exe -P -ImageDescription="Box Front" "01 Box Front/*.jpg"
exiftool.exe -P -ImageDescription="Box Back" "02 Box Back/*.jpg"
exiftool.exe -P -ImageDescription="Cartridge" "03 Cartridge/*.jpg"
exiftool.exe -P -ImageDescription="Cartridge" "04 Cartridge Text/*.jpg"
exiftool.exe -P -ImageDescription="Tape" "05 Tape/*.jpg"
exiftool.exe -P -ImageDescription="Tape" "06 Tape/*.jpg"
exiftool.exe -P -ImageDescription="Tape" "07 Tape/*.jpg"
exiftool.exe -P -ImageDescription="End Label" "08 End Label/*.jpg"
exiftool.exe -P -ImageDescription="Board" "09 Board/*.jpg"
exiftool.exe -P -ImageDescription="Board" "10 Board/*.jpg"
exiftool.exe -P -ImageDescription="Board" "11 Board/*.jpg"
exiftool.exe -P -ImageDescription="Miscellaneous" "12 miscellaneous/*.jpg"
exiftool.exe -P -ImageDescription="Miscellaneous" "13 miscellaneous/*.jpg"
exiftool.exe -P -ImageDescription="Miscellaneous" "14 miscellaneous/*.jpg"
exiftool.exe -P -ImageDescription="Miscellaneous" "15 miscellaneous/*.jpg"
exiftool.exe -P -ImageDescription="Miscellaneous" "16 miscellaneous/*.jpg"
exiftool.exe -P -ImageDescription="Miscellaneous" "17 miscellaneous/*.jpg"
exiftool.exe -P -ImageDescription="Patch" "18 patches/*.jpg"
exiftool.exe -P -ImageDescription="Patch" "19 patches/*.jpg"
exiftool.exe -P -ImageDescription="Patch" "20 patches/*.jpg"
exiftool.exe -P -ImageDescription="Patch" "21 patches/*.jpg"

exiftool.exe -P -ImageDescription="Box Front" "22 box front alternate/*.jpg"
exiftool.exe -P -ImageDescription="Box Front" "23 box front alternate/*.jpg"
exiftool.exe -P -ImageDescription="Box Back" "24 box back alternate/*.jpg"
exiftool.exe -P -ImageDescription="Cartridge" "25 cartridge alternate/*.jpg"
exiftool.exe -P -ImageDescription="Cartridge" "26 cartridge alternate/*.jpg"
exiftool.exe -P -ImageDescription="Cartridge" "27 cartridge text alternate/*.jpg"
exiftool.exe -P -ImageDescription="Cartridge" "28 cartridge label alternate/*.jpg"
exiftool.exe -P -ImageDescription="Miscellaneous" "29 miscellaneous/*.jpg"
exiftool.exe -P -ImageDescription="Miscellaneous" "30 miscellaneous/*.jpg"
exiftool.exe -P -ImageDescription="Miscellaneous" "31 miscellaneous/*.jpg"
exiftool.exe -P -ImageDescription="Miscellaneous" "32 miscellaneous/*.jpg"
exiftool.exe -P -ImageDescription="Miscellaneous" "33 miscellaneous/*.jpg"

del /s *.jpg_original
