forfiles /P "01 Box Front" 		   /M *.jpg /C "cmd /c rename @file @fname_100.jpg"
forfiles /P "02 Box Back" 		   /M *.jpg /C "cmd /c rename @file @fname_200.jpg"
forfiles /P "03 Cartridge" 		   /M *.jpg /C "cmd /c rename @file @fname_300.jpg"
forfiles /P "04 Cartridge Text" 	   /M *.jpg /C "cmd /c rename @file @fname_301.jpg"
forfiles /P "05 Tape" 			   /M *.jpg /C "cmd /c rename @file @fname_600.jpg"
forfiles /P "06 Tape" 			   /M *.jpg /C "cmd /c rename @file @fname_601.jpg"
forfiles /P "07 Tape" 			   /M *.jpg /C "cmd /c rename @file @fname_602.jpg"
forfiles /P "08 End Label" 		   /M *.jpg /C "cmd /c rename @file @fname_400.jpg"
forfiles /P "09 Board" 			   /M *.jpg /C "cmd /c rename @file @fname_900.jpg"
forfiles /P "10 Board" 			   /M *.jpg /C "cmd /c rename @file @fname_901.jpg"
forfiles /P "11 Board" 			   /M *.jpg /C "cmd /c rename @file @fname_902.jpg"
forfiles /P "12 miscellaneous" 		   /M *.jpg /C "cmd /c rename @file @fname_700.jpg"
forfiles /P "13 miscellaneous" 		   /M *.jpg /C "cmd /c rename @file @fname_701.jpg"
forfiles /P "14 miscellaneous" 		   /M *.jpg /C "cmd /c rename @file @fname_702.jpg"
forfiles /P "15 miscellaneous" 		   /M *.jpg /C "cmd /c rename @file @fname_703.jpg"
forfiles /P "16 miscellaneous" 		   /M *.jpg /C "cmd /c rename @file @fname_704.jpg"
forfiles /P "17 miscellaneous" 		   /M *.jpg /C "cmd /c rename @file @fname_705.jpg"
forfiles /P "18 patches" 		   /M *.jpg /C "cmd /c rename @file @fname_800.jpg"
forfiles /P "19 patches" 		   /M *.jpg /C "cmd /c rename @file @fname_801.jpg"
forfiles /P "20 patches" 		   /M *.jpg /C "cmd /c rename @file @fname_802.jpg"
forfiles /P "21 patches" 		   /M *.jpg /C "cmd /c rename @file @fname_803.jpg"

forfiles /P "22 box front alternate" 	   /M *.jpg /C "cmd /c rename @file @fname_101.jpg"
forfiles /P "23 box front alternate" 	   /M *.jpg /C "cmd /c rename @file @fname_102.jpg"
forfiles /P "24 box back alternate" 	   /M *.jpg /C "cmd /c rename @file @fname_201.jpg"
forfiles /P "25 cartridge alternate" 	   /M *.jpg /C "cmd /c rename @file @fname_302.jpg"
forfiles /P "26 cartridge alternate" 	   /M *.jpg /C "cmd /c rename @file @fname_303.jpg"
forfiles /P "27 cartridge text alternate"  /M *.jpg /C "cmd /c rename @file @fname_304.jpg"
forfiles /P "28 cartridge label alternate" /M *.jpg /C "cmd /c rename @file @fname_305.jpg"
forfiles /P "29 miscellaneous" 		   /M *.jpg /C "cmd /c rename @file @fname_706.jpg"
forfiles /P "30 miscellaneous" 		   /M *.jpg /C "cmd /c rename @file @fname_707.jpg"
forfiles /P "31 miscellaneous" 		   /M *.jpg /C "cmd /c rename @file @fname_708.jpg"
forfiles /P "32 miscellaneous" 		   /M *.jpg /C "cmd /c rename @file @fname_709.jpg"
forfiles /P "33 miscellaneous" 		   /M *.jpg /C "cmd /c rename @file @fname_710.jpg"





