
#ifndef _SNTIMING_H
#define _SNTIMING_H

#define SNES_CYCLESPERLINE (1364)

#define SNES_LINECYCLEDELAY (40)
#define SNES_HBLANKCYCLES  (SNES_CYCLESPERLINE - 1024)
#define SNES_SPCMINCYCLES 0
#define SNES_CYCLESPERFRAME (SNES_CYCLESPERLINE * 262)


#endif

