source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def commonDependencies
    pod 'RxGesture', :path => '../'
    pod 'RxSwift', '~> 4.3'
    pod 'RxSwift', '~> 4.3'
end

target 'RxGesture_iOS_Demo' do
    platform :ios, '8.0'
    commonDependencies
end

target 'RxGesture_OSX_Demo' do
    platform :osx, '10.10'
    commonDependencies
end
