# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../libretro_ppsspp/ext/cmake/cpu_features/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../libretro_ppsspp/ext/cpu_features/cmake/CpuFeaturesConfig.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/BasicConfigVersion-SameMajorVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/CheckSymbolExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard ../cmake/CMakeFiles/cmake.verify_globs))

.NOTPARALLEL:

.PHONY: all VERIFY_GLOBS

all: VERIFY_GLOBS ../cmake/CMakeFiles/cmake.check_cache

VERIFY_GLOBS:
	/usr/local/Cellar/cmake/3.26.4/bin/cmake -P ../cmake/CMakeFiles/VerifyGlobs.cmake

../cmake/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.26.4/bin/cmake -H../libretro_ppsspp -B../cmake
