#!/bin/bash
# validate_frameworks.sh — Post-build sanity check for RetroArch libretro frameworks
# Run as an Xcode "Run Script" build phase AFTER "Generate Frameworks" and "Embed Frameworks".
#
# Fails the build if the app bundle is missing libretro core frameworks that should
# have been generated by make_frameworks_retroarch.sh.

set -euo pipefail

APP_FRAMEWORKS="${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}"

if [ ! -d "$APP_FRAMEWORKS" ]; then
    echo "ValidateFrameworks: ERROR — Frameworks directory does not exist: $APP_FRAMEWORKS" >&2
    exit 1
fi

# Count libretro core frameworks in the app bundle
LIBRETRO_COUNT=$(find "$APP_FRAMEWORKS" -maxdepth 1 -type d -name "*.libretro.framework" 2>/dev/null | wc -l | tr -d ' ')

# Count PVRetroArch.framework (the bridge)
HAS_BRIDGE=$(find "$APP_FRAMEWORKS" -maxdepth 1 -type d -name "PVRetroArch.framework" 2>/dev/null | wc -l | tr -d ' ')

echo "ValidateFrameworks: Found ${LIBRETRO_COUNT} libretro core frameworks in app bundle"
echo "ValidateFrameworks: PVRetroArch bridge present: $([ "$HAS_BRIDGE" -gt 0 ] && echo YES || echo NO)"

# If the bridge is present, cores MUST also be present
if [ "$HAS_BRIDGE" -gt 0 ] && [ "$LIBRETRO_COUNT" -eq 0 ]; then
    echo "ValidateFrameworks: ERROR — PVRetroArch.framework is embedded but 0 libretro core frameworks found!" >&2
    echo "ValidateFrameworks: ERROR — The 'Generate Frameworks' build phase likely failed silently." >&2
    echo "ValidateFrameworks: ERROR — Check the build log for make_frameworks_retroarch.sh errors." >&2
    # List what IS in the Frameworks dir for debugging
    echo "ValidateFrameworks: Contents of $APP_FRAMEWORKS:" >&2
    ls -1 "$APP_FRAMEWORKS" | head -30 >&2
    exit 1
fi

# Warn if suspiciously few cores (expect at least 10 for AppStore/XL builds)
if [ "$LIBRETRO_COUNT" -gt 0 ] && [ "$LIBRETRO_COUNT" -lt 10 ]; then
    echo "ValidateFrameworks: WARNING — only ${LIBRETRO_COUNT} libretro frameworks found (expected 10+)" >&2
fi

# Spot-check: verify a framework actually has an executable inside
SAMPLE_FW=$(find "$APP_FRAMEWORKS" -maxdepth 1 -type d -name "*.libretro.framework" 2>/dev/null | head -1)
if [ -n "$SAMPLE_FW" ]; then
    FW_NAME=$(basename "$SAMPLE_FW" .framework)
    if [ ! -f "$SAMPLE_FW/$FW_NAME" ] && [ ! -L "$SAMPLE_FW/$FW_NAME" ]; then
        echo "ValidateFrameworks: ERROR — $FW_NAME.framework exists but has no executable!" >&2
        echo "ValidateFrameworks: ERROR — Framework is an empty shell. lipo/vtool likely failed." >&2
        ls -la "$SAMPLE_FW/" >&2
        exit 1
    fi
fi

echo "ValidateFrameworks: OK — ${LIBRETRO_COUNT} core frameworks validated"
exit 0
